#!/usr/bin/env python3
"""Regenerate reviewed adaptation inputs from an original zip and edited copy.

This is a maintainer tool, not part of builds. Review the emitted changes and
both pin files before committing. It never writes the original archive or copy.
"""
import argparse
import base64
import difflib
import hashlib
import json
import pathlib
import zipfile

MODULE = "tailscale.com"
VERSION = "v1.104.0"
MODULE_SUM = "h1:7LgglawekeutAexqXUzSxP/Kqo3HHwF/SkcbX5HpiU4="
MOD_SUM = "h1:Cb1XjScRgSOeRD7NW6uCEznme782WiOU9IxqyTWoRf0="
# Changing this allowlist is a separate source-review decision. Never capture
# ambient logs, binaries, checkpoints or unrelated source from an edited copy.
ALLOWED_PATHS = {
    "wgengine/userspace.go", "wgengine/magicsock/magicsock.go",
    "wgengine/magicsock/rebinding_conn.go", "wgengine/magicsock/derp.go",
    "wgengine/magicsock/magicsock_linux.go", "derp/derphttp/derphttp_client.go",
    "net/netcheck/netcheck.go", "net/netcheck/standalone.go",
    "net/underlayguard/policy.go", "net/underlayguard/policy_test.go",
    "wgengine/underlay_guard_test.go", "wgengine/magicsock/underlay_guard_test.go",
    "wgengine/magicsock/underlay_guard_linux_test.go", "derp/derphttp/underlay_guard_test.go",
    "net/netcheck/underlay_guard_test.go", "net/underlayguard/LICENSE",
    "wgengine/magicsock/endpoint_test.go",
}



def sha(data):
    return hashlib.sha256(data).hexdigest()


def listing(tree):
    return "".join(sha(tree[path]) + "  " + path + "\n" for path in sorted(tree)).encode()


def h1(tree):
    return "h1:" + base64.b64encode(hashlib.sha256(listing(tree)).digest()).decode()


def generate(archive, adapted, root):
    prefix = MODULE + "@" + VERSION + "/"
    with zipfile.ZipFile(archive) as z:
        original = {}
        for entry in z.infolist():
            if entry.is_dir():
                continue
            assert entry.filename.startswith(prefix)
            path = entry.filename[len(prefix):]
            assert path not in original
            assert not pathlib.PurePosixPath(path).is_absolute() and ".." not in pathlib.PurePosixPath(path).parts
            original[path] = z.read(entry)
    assert h1({prefix + p: b for p, b in original.items()}) == MODULE_SUM
    assert h1({"go.mod": original["go.mod"]}) == MOD_SUM
    final = {}
    for p in adapted.rglob("*"):
        assert not p.is_symlink(), "links are not adaptation inputs"
        if p.is_dir():
            continue
        assert p.is_file()
        final[p.relative_to(adapted).as_posix()] = p.read_bytes()
    assert final.keys() - original.keys() <= ALLOWED_PATHS, "unreviewed extra file in adapted copy"
    assert original.keys() <= final.keys(), "file deletion requires a separate reviewed format change"
    assert original["go.mod"] == final["go.mod"] and original["go.sum"] == final["go.sum"]
    changes = []
    for path in sorted(final):
        before, after = original.get(path, b""), final[path]
        if before == after and path in original:
            continue
        assert path in ALLOWED_PATHS, "unreviewed changed or added path: " + path
        oldlines, newlines = before.splitlines(keepends=True), after.splitlines(keepends=True)
        edits = []
        for op, a, b, c, d in difflib.SequenceMatcher(None, oldlines, newlines, autojunk=False).get_opcodes():
            if op != "equal":
                edits.append({"offset": sum(map(len, oldlines[:a])), "old": b"".join(oldlines[a:b]).decode(), "new": b"".join(newlines[c:d]).decode()})
        changes.append({"path": path, "original_sha256": sha(before) if path in original else "", "adapted_sha256": sha(after), "edits": edits})
    assert changes, "no adaptation"
    manifest = {"schema": 1, "module": MODULE, "version": VERSION, "module_sum": MODULE_SUM, "go_mod_sum": MOD_SUM,
                "source_url": "https://github.com/tailscale/tailscale/tree/" + VERSION,
                "upstream_tree_sha256": sha(listing(original)), "adapted_tree_sha256": sha(listing(final)), "changes": changes}
    raw = (json.dumps(manifest, indent=2, ensure_ascii=False) + "\n").encode()
    output = root / "internal" / "engineadaptation"
    (output / "manifest.json").write_bytes(raw)
    (output / "pin.go").write_text('// Code generated by update-engine-manifest.py; review both this pin and manifest.\npackage engineadaptation\n\nconst ManifestSHA256 = "' + sha(raw) + '"\n')
    print("Review", len(changes), "changed or added paths; compact manifest bytes:", len(raw))
    for change in changes:
        print(change["path"])


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("original_zip", type=pathlib.Path)
    parser.add_argument("adapted_directory", type=pathlib.Path)
    args = parser.parse_args()
    generate(args.original_zip, args.adapted_directory, pathlib.Path(__file__).resolve().parents[2])
