import { test, expect } from './fixtures.mjs'

// All identities and public keys are fictional. The existing Go fixture runs
// Core and the production UI; these cases never configure an external client.
for (const locale of ['en', 'ja']) {
  test(`${locale}: RustDesk save-only review, cancellation, settings and separate group start review`, async ({ page, app }) => {
    const ja = locale === 'ja'
    await app.appearance(locale, ja ? 'dark' : 'light')
    await page.getByRole('button', { name: ja ? '保存済みサービス' : 'Saved services', exact: true }).click()
    await page.getByText(ja ? '接続設定の補助' : 'Connection helpers', { exact: true }).click()
    await page.getByRole('button', { name: ja ? 'RustDesk グループを保存' : 'Save a RustDesk group', exact: true }).click()
    const dialog = page.getByRole('dialog')
    const id = dialog.getByRole('group', { name: ja ? 'ID サーバーの端末' : 'ID server device', exact: true })
    const relay = dialog.getByRole('group', { name: ja ? 'リレーサーバーの端末' : 'Relay server device', exact: true })
    await id.getByRole('combobox').selectOption('fixture-studio')
    await relay.getByRole('textbox').fill('fictional-offline-relay')
    await dialog.getByLabel(ja ? 'RustDesk サーバーの公開鍵' : 'RustDesk server public key', { exact: true }).fill('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')
    await dialog.getByRole('button', { name: ja ? '4つの通信経路を確認' : 'Review four flows', exact: true }).click()
    const review = dialog.getByRole('region', { name: ja ? 'RustDesk グループを確認' : 'Review RustDesk group', exact: true })
    await expect(review.locator('.client-flows article')).toHaveCount(4)
    await expect(review).toContainText('127.0.0.1:32115 → 21115')
    await expect(review).toContainText('fictional-offline-relay')
    await expect(review).toContainText(ja ? '予定・未保存' : 'Planned / not saved')
    expect(await app.count('rustdesk.save')).toBe(0)
    await app.captureForm(`rustdesk-review-${locale}-desktop`)
    await review.getByRole('button', { name: ja ? '設定に戻る' : 'Back to settings', exact: true }).click()
    await dialog.getByRole('button', { name: ja ? 'キャンセル' : 'Cancel', exact: true }).click()
    expect(await app.count('rustdesk.save')).toBe(0)
    await page.getByText(ja ? '接続設定の補助' : 'Connection helpers', { exact: true }).click()
    await page.getByRole('button', { name: ja ? 'RustDesk グループを保存' : 'Save a RustDesk group', exact: true }).click()
    await id.getByRole('combobox').selectOption('fixture-studio')
    await relay.getByRole('textbox').fill('fictional-offline-relay')
    await dialog.getByLabel(ja ? 'RustDesk サーバーの公開鍵' : 'RustDesk server public key', { exact: true }).fill('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')
    await dialog.getByRole('button', { name: ja ? '4つの通信経路を確認' : 'Review four flows', exact: true }).click()
    await dialog.getByRole('button', { name: ja ? '確認したグループを保存' : 'Save reviewed group', exact: true }).click()
    await expect(dialog.getByRole('status')).toContainText(ja ? 'サービスは開始していません' : 'No services were started')
    await app.expectState(state => state.services.filter(service => service.name.startsWith('rustdesk-') && service.status === 'saved').length === 4)
    await dialog.getByRole('button', { name: ja ? '保存済みグループを開く' : 'Open saved group', exact: true }).click()
    await expect(dialog.getByRole('combobox', { name: ja ? '保存済みグループ' : 'Saved group', exact: true })).toHaveValue('rustdesk')
    await page.getByText(ja ? '接続設定の補助' : 'Connection helpers', { exact: true }).click()
    await dialog.getByRole('button', { name: ja ? '選択したサービスの設定' : 'Settings for selected services', exact: true }).click()
    await expect(dialog.getByLabel(ja ? 'リレーサーバー設定' : 'Relay server setting', { exact: true })).toHaveValue('127.0.0.1:32117')
    await expect(dialog).toContainText(ja ? '同じローカルリレーアドレスとポート' : 'same local relay address and port')
    await page.setViewportSize({ width: 390, height: 844 })
    await app.captureForm(`rustdesk-settings-${locale}-390`)
    await page.keyboard.press('Escape')
    await dialog.getByRole('button', { name: ja ? '開始内容を確認' : 'Review start', exact: true }).click()
    await dialog.getByRole('combobox', { name: ja ? '今回の開始に使う有効期間' : 'Lifetime for this start', exact: true }).selectOption('custom')
    await dialog.getByLabel(ja ? '有効期間（秒）' : 'Duration in seconds', { exact: true }).fill('120')
    const groupReview = dialog.getByRole('region', { name: ja ? '選択したサービスを確認' : 'Review selected services', exact: true })
    await expect(groupReview).toContainText(ja ? '保存済み定義は変更しません' : 'saved definitions stay unchanged')
    await groupReview.getByRole('button', { name: ja ? 'キャンセル' : 'Cancel', exact: true }).click()
    expect(await app.count('services.start')).toBe(0)
    expect(await app.count('service.connect')).toBe(0)
  })
}

test('saved HTTP hints retain TLS cautions and a reviewed runtime lifetime does not change the saved definition', async ({ page, app }) => {
  await page.getByRole('button', { name: 'Saved services', exact: true }).click()
  await page.getByRole('button', { name: 'Save a connection', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('Connection name', { exact: true }).fill('fictional-web-client')
  await dialog.getByRole('combobox', { name: /Saved network/ }).selectOption('tailnet')
  await dialog.getByRole('textbox', { name: /Exact device IDs/ }).fill('fixture-studio')
  await dialog.getByLabel('Ports', { exact: true }).fill('8080')
  await dialog.getByLabel('Local starting port', { exact: true }).fill(String(app.localServicePort))
  await dialog.getByLabel('Purpose', { exact: true }).fill('web')
  await dialog.getByRole('button', { name: 'Review stopped definition', exact: true }).click()
  await dialog.getByRole('button', { name: 'Save reviewed definition', exact: true }).click()
  await dialog.getByRole('button', { name: 'Client settings', exact: true }).click()
  await expect(dialog.getByLabel('HTTP candidate', { exact: true })).toHaveValue(`http://127.0.0.1:${app.localServicePort}/`)
  await expect(dialog).toContainText('original TLS hostname, SNI, origin and certificate validation')
  await expect(dialog.getByRole('link')).toHaveCount(0)
  await page.keyboard.press('Escape')
  await dialog.getByRole('button', { name: 'Select all', exact: true }).click()
  await dialog.getByRole('button', { name: 'Review start', exact: true }).click()
  await dialog.getByLabel('Lifetime for this start', { exact: true }).selectOption('custom')
  await dialog.getByLabel('Duration in seconds', { exact: true }).fill('120')
  await dialog.getByRole('button', { name: 'Start reviewed services', exact: true }).click()
  await app.expectState(state => state.services.some(service => service.name === 'fictional-web-client' && service.status === 'active' && service.lifetime === 'finite' && service.ttlSeconds === 120))
  await dialog.getByRole('button', { name: 'Review stop', exact: true }).click()
  await dialog.getByRole('button', { name: 'Stop reviewed services', exact: true }).click()
  await app.expectState(state => state.services.some(service => service.name === 'fictional-web-client' && service.status === 'stopped' && service.lifetime === 'until-stopped'))
  expect(await app.count('services.start')).toBe(1)
  expect(await app.count('service.save')).toBe(1)
})
