import { test, expect } from './fixtures.mjs'

test.describe('explicit initial LAN destination policy', () => {
  test.use({ scenario: 'offline' })
  for (const locale of ['en', 'ja']) {
    test(`${locale}: select synthetic prefix, review before start, cancel and inspect narrow layout`, async ({ page, app }) => {
      await app.appearance(locale, locale === 'ja' ? 'dark' : 'light')
      await page.locator('.sidebar-title button').click()
      await page.locator('dialog input[value=lan]').check()
      const policy = page.locator('.lan-policy')
      await expect(policy).not.toHaveAttribute('open')
      await policy.locator(':scope > summary').click()
      await expect(policy.locator('select')).toHaveValue('trusted-relay')
      await policy.locator('select').selectOption('allowed-lan-destinations')
      await expect(policy.locator('textarea')).toHaveValue('')
      await policy.getByRole('button', { name: locale === 'ja' ? 'ローカルの範囲候補を表示' : 'Show local prefix suggestions', exact: true }).click()
      await expect(policy.locator('textarea')).toHaveValue('')
      expect(await app.count('lan.policy.set')).toBe(0)
      expect(await app.count('network.configure')).toBe(0)
      await policy.getByRole('button', { name: /192\.168\.50\.0\/24 · fixture0/ }).click()
      await expect(policy.locator('textarea')).toHaveValue('192.168.50.0/24')
      const host = page.locator('.relay-host')
      await host.locator('select').selectOption({ label: '192.168.50.10 · fixture0' })
      await host.locator('button[type=submit]').click()
      const review = host.locator('.relay-review')
      await expect(review).toContainText('192.168.50.0/24')
      await expect(review).toContainText(locale === 'ja' ? '物理LANやVPN' : 'physical LAN or VPN')
      expect(await app.count('network.configure')).toBe(0)
      await review.scrollIntoViewIfNeeded()
      await app.capture(`lan-policy-review-${locale}-desktop`)
      await page.setViewportSize({ width: 390, height: 844 })
      await review.scrollIntoViewIfNeeded()
      await app.capture(`lan-policy-review-${locale}-390`)
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
      await review.getByRole('button', { name: locale === 'ja' ? 'キャンセル' : 'Cancel', exact: true }).click()
      await expect(host.locator('.relay-review')).toHaveCount(0)
      expect(await app.count('network.configure')).toBe(0)
      expect(await app.count('lan.policy.set')).toBe(0)
    })
  }
})
