import { test, expect } from './fixtures.mjs'

test.describe('offline setup', () => {
  test.use({ scenario: 'offline' })
  for (const locale of ['en', 'ja']) {
    test(`${locale}: empty navigation, guided host review, validation and offline Stop cancellation`, async ({ page, app }) => {
      await app.appearance(locale, locale === 'ja' ? 'dark' : 'light')
      await expect(page.locator('.sidebar-empty')).toBeVisible()
      await app.capture(`offline-empty-${locale}-desktop`)
      await page.locator('.network-map-button').click()
      await expect(page.locator('.network-graph-empty')).toBeVisible()
      await expect(page.locator('.network-graph-edge')).toHaveCount(0)
      await app.capture(`offline-graph-${locale}-desktop`)
      await page.locator('.devices-view-button').click()
      await expect(page.locator('.network-graph')).toHaveAttribute('data-view', 'list')
      await page.locator('.sidebar-title button').click()
      await expect(page.getByRole('dialog')).toBeVisible()
      const stopName = locale === 'ja' ? 'sobalink を停止' : 'Stop sobalink'
      const cancelName = locale === 'ja' ? 'キャンセル' : 'Cancel'
      await page.getByRole('button', { name: stopName, exact: true }).click()
      await expect(page.locator('.relay-stop-review')).toBeFocused()
      await expect(page.locator('.relay-stop-review dl dd').last()).toHaveText('0')
      await page.locator('.relay-stop-review').scrollIntoViewIfNeeded()
      await app.capture(`offline-stop-review-${locale}`)
      await page.getByRole('button', { name: cancelName, exact: true }).click()
      await expect(page.locator('.relay-stop-review')).toHaveCount(0)
      expect(await app.count('application.stop')).toBe(0)
      expect(await app.count('network.configure')).toBe(0)
      await page.locator('dialog input[value=lan]').check()
      const host = page.locator('.relay-host')
      await expect(host).toBeVisible()
      await expect(host.locator('input[type=number]')).toHaveValue('48443')
      await expect(host.locator('select')).toHaveValue('')
      await expect(host.locator('select option')).toHaveCount(2)
      await app.capture(`offline-lan-host-${locale}-desktop`)
      await host.locator('select').selectOption({ label: '192.168.50.10 · fixture0' })
      await host.locator('button[type=submit]').click()
      await expect(page.locator('.relay-review')).toContainText('192.168.50.10:48443')
      await app.capture(`offline-lan-host-review-${locale}`)
      await page.locator('.relay-review').getByRole('button', { name: cancelName, exact: true }).click()
      expect(await app.count('network.configure'), 'reviewing an interface must not start a host').toBe(0)
      const manualName = locale === 'ja' ? 'LANアドレスを手入力する' : 'Enter a LAN address manually'
      await host.getByRole('checkbox', { name: manualName, exact: true }).check()
      const manualAddress = host.locator('input[maxlength="45"]')
      await manualAddress.fill('0.0.0.0')
      await host.locator('button[type=submit]').click()
      await expect(host.getByRole('alert')).toBeVisible()
      expect(await app.count('network.configure'), 'manual fallback must not permit a wildcard listener').toBe(0)
      await manualAddress.fill('FD00:0:0:0:0:0:0:5')
      await host.locator('button[type=submit]').click()
      await expect(host.locator('.relay-review')).toContainText('[fd00::5]:48443')
      await page.setViewportSize({ width: 390, height: 844 })
      await app.capture(`offline-lan-manual-review-${locale}-390`)
      await host.getByRole('button', { name: cancelName, exact: true }).click()
      await expect(manualAddress).toHaveValue('FD00:0:0:0:0:0:0:5')
      expect(await app.count('network.configure'), 'manual review and cancellation must not start a host').toBe(0)
      await page.setViewportSize({ width: 1280, height: 900 })
      await page.locator('.manual-relay > summary').click()
      const relay = page.locator('.manual-relay')
      const relayAddress = relay.getByRole('textbox', { name: locale === 'ja' ? /^リレーのアドレス/ : /^Relay address/ })
      await relayAddress.fill('invalid.example:443')
      await relay.locator('input[maxlength="64"]').fill('0'.repeat(64))
      await relay.locator('button[type=submit]').click()
      await expect(page.getByRole('alert')).toBeVisible()
      expect(await app.count('network.configure'), 'a hostname must not pass numeric relay address validation').toBe(0)
      await relayAddress.fill('127.0.0.1:443')
      await relay.locator('input[maxlength="64"]').fill('invalid-pin')
      await relay.locator('button[type=submit]').click()
      await expect(page.getByRole('alert')).toContainText('64')
      expect(await app.count('network.configure'), 'an invalid pin must not activate LAN').toBe(0)
      await app.capture(`offline-lan-invalid-${locale}`)
      await page.keyboard.press('Escape')
      await page.setViewportSize({ width: 390, height: 844 })
      await app.capture(`offline-list-${locale}-390`)
    })
  }
})

test.describe('whole-application shutdown', () => {
  test.use({ expectShutdown: true })
  test('active service survives cancellation, then one confirmed Stop closes the actual application', async ({ page, app }) => {
    await app.appearance('en', 'light')
    await app.openPeer()
    await page.getByRole('button', { name: 'Connect to a service', exact: true }).click()
    await page.locator('dialog input[required][maxlength="64"]').fill('shutdown-review-service')
    await page.locator('dialog input[aria-describedby=port-help]').fill('8080')
    await page.locator('dialog input[inputmode=numeric]').fill(String(app.localServicePort))
    await page.locator('dialog button[type=submit]').click()
    await app.expectState(state => state.services.some(service => service.name === 'shutdown-review-service' && service.status === 'active'), 'shutdown review starts with a real active loopback service')
    await expect(page.locator('dialog[open]')).toHaveCount(0)
    await app.closeDetails()
    await page.locator('.sidebar-title button').click()
    await page.getByRole('button', { name: 'Stop sobalink', exact: true }).click()
    await expect(page.locator('.relay-stop-review dl dd').last()).toHaveText('1')
    await expect(page.locator('.relay-stop-review')).toContainText('This control page will disconnect')
    await page.locator('.relay-stop-review').scrollIntoViewIfNeeded()
    await app.capture('application-stop-review-en-light')
    await page.getByRole('button', { name: 'Cancel', exact: true }).click()
    expect(await app.count('application.stop')).toBe(0)
    await app.expectState(state => state.services.some(service => service.name === 'shutdown-review-service' && service.status === 'active'), 'cancelling whole-app Stop preserves the active service')
    await page.keyboard.press('Escape')
    await app.appearance('ja', 'dark')
    await page.locator('.sidebar-title button').click()
    await page.getByRole('button', { name: 'sobalink を停止', exact: true }).click()
    await page.setViewportSize({ width: 390, height: 844 })
    await page.locator('.relay-stop-review .invitation-actions').scrollIntoViewIfNeeded()
    await app.capture('application-stop-review-ja-dark-390')
    await page.getByRole('button', { name: 'アプリと接続を停止', exact: true }).click()
    await expect(page.locator('dialog [role=status]').filter({ hasText: '停止を要求しました' })).toBeVisible()
    expect(await app.count('application.stop')).toBe(1)
    await expect(page.locator('.relay-stop-review .button-danger')).toBeDisabled()
    await app.capture('application-stopping-ja-dark-390')
    // All assertions after Stop observe the loaded page or process lifecycle;
    // no live-state HTTP request is used as proof of shutdown.
    await app.expectStopped()
  })
})

test('checking a connected Tailnet shows status without generating sign-in details', async ({ page, app }) => {
  await app.appearance('en', 'light')
  await page.locator('.sidebar-title button').click()
  expect(await app.count('network.login')).toBe(0)
  expect(await app.count('network.login.status')).toBe(0)
  await page.getByRole('button', { name: 'Check sign-in status', exact: true }).click()
  await expect(page.getByText('This device is connected', { exact: true })).toBeVisible()
  await expect(page.locator('.signin-link, .auth-qr')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Sign in to Tailscale', exact: true })).toHaveCount(0)
  expect(await app.count('network.login')).toBe(0)
  expect(await app.count('network.login.status')).toBe(1)
  await app.capture('connected-tailnet-status-en-light')
  await page.keyboard.press('Escape')
  await page.locator('.sidebar-title button').click()
  await expect(page.locator('.signin-link, .auth-qr')).toHaveCount(0)
  expect(await app.count('network.login.status')).toBe(1)
})
