import { test, expect } from './fixtures.mjs'

// Synthetic saved definitions through the Go-backed offline harness. No live
// application grant, listener, enrollment or real-device claim is made here.
test.use({ scenario: 'offline' })
for (const locale of ['en', 'ja']) {
  test(`${locale}: saved share templates preserve scope, require review and stay stopped`, async ({ page, app }) => {
    const ja = locale === 'ja'
    await app.appearance(locale, ja ? 'dark' : 'light')
    await page.getByRole('button', { name: ja ? '保存済みサービス' : 'Saved services', exact: true }).click()
    const dialog = page.getByRole('dialog')
    const create = () => dialog.getByRole('button', { name: ja ? '共有定義を保存' : 'Save a share', exact: true })
    const name = () => dialog.getByLabel(ja ? '接続の名前' : 'Connection name', { exact: true })
    const review = () => dialog.getByRole('button', { name: ja ? '停止状態の定義を確認' : 'Review stopped definition', exact: true })
    const save = () => dialog.getByRole('button', { name: ja ? '確認した定義を保存' : 'Save reviewed definition', exact: true })
    const audience = () => dialog.getByRole('textbox', { name: new RegExp(ja ? '正確な端末 ID' : 'Exact device IDs') })
    await create().click()
    await name().fill('fixture-share-template')
    await dialog.getByRole('combobox', { name: new RegExp(ja ? '保存するネットワーク' : 'Saved network') }).selectOption('tailnet')
    await audience().fill('fixture-absent, fixture-other')
    await dialog.getByLabel(ja ? 'ポート' : 'Ports', { exact: true }).fill('18080-18082')
    await dialog.getByLabel(ja ? '除外するポート' : 'Exclude ports', { exact: true }).fill('18081')
    await dialog.getByLabel(ja ? '有効期間（秒）' : 'Duration in seconds', { exact: true }).fill('259200')
    await dialog.getByRole('checkbox').check()
    await review().click(); await save().click()
    await expect(create()).toBeVisible()
    await create().click()
    const templates = dialog.getByRole('combobox', { name: new RegExp(ja ? '保存済み共有をひな形にする' : 'Start from saved share') })
    await templates.selectOption({ label: 'fixture-share-template · TCP · 18080-18082' })
    await expect(name()).toHaveValue('fixture-share-template-2')
    await expect(audience()).toHaveValue('fixture-absent, fixture-other')
    await expect(dialog.getByRole('checkbox')).toBeChecked()
    await review().click()
    const scope = dialog.getByRole('region', { name: ja ? '保存する範囲を確認' : 'Review saved scope', exact: true })
    for (const value of ['fixture-absent, fixture-other', '18080-18082', '18081', '259200']) await expect(scope).toContainText(value)
    expect(await app.count('service.save')).toBe(1)
    await dialog.getByRole('button', { name: ja ? 'この下書きを編集' : 'Edit this draft', exact: true }).click()
    await expect(scope).toHaveCount(0)
    await dialog.getByLabel(ja ? 'ポート' : 'Ports', { exact: true }).fill('19080-19082')
    await dialog.getByLabel(ja ? '除外するポート' : 'Exclude ports', { exact: true }).fill('19081')
    await audience().fill('fixture-absent')
    await review().click()
    await expect(scope).toContainText('19080-19082'); await expect(scope).not.toContainText('fixture-other')
    for (const viewport of [{ width: 1440, height: 960 }, { width: 375, height: 844 }, { width: 844, height: 390 }]) {
      await page.setViewportSize(viewport)
      const edit = dialog.getByRole('button', { name: ja ? 'この下書きを編集' : 'Edit this draft', exact: true })
      await edit.scrollIntoViewIfNeeded(); await edit.focus(); await expect(edit).toBeFocused()
      await page.keyboard.press('Tab'); await expect(save()).toBeFocused()
      await expect.poll(() => dialog.evaluate(element => {
        const body = element.querySelector('.modal-body')
        const bounds = document.activeElement.getBoundingClientRect()
        const top = document.elementFromPoint(bounds.left + bounds.width / 2, bounds.top + bounds.height / 2)
        return body.scrollWidth <= body.clientWidth + 1 && bounds.left >= 0 && bounds.right <= innerWidth && bounds.top >= 0 && bounds.bottom <= innerHeight && Boolean(top && document.activeElement.contains(top))
      }), { message: 'Template review and focused save control stay inside desktop and narrow viewports' }).toBe(true)
      await expect(dialog.locator('.modal-actions')).toHaveCount(1)
      await app.captureForm(`sharing-template-${locale}-${viewport.width}x${viewport.height}`)
    }
    await save().click(); await expect(create()).toBeVisible()
    await app.expectState(state => state.shares.some(service => service.name === 'fixture-share-template-2' && service.status === 'saved') && !state.shares.some(service => ['active', 'reconnecting'].includes(service.status)), 'Copied share is saved and stopped')
    await create().click(); await templates.selectOption({ label: 'fixture-share-template · TCP · 18080-18082' })
    await expect(name()).toHaveValue('fixture-share-template-3')
    await review().click(); await page.keyboard.press('Escape')
    await expect(create()).toBeVisible()
    expect(await app.count('service.save')).toBe(2)
    for (const command of ['service.connect', 'service.share', 'services.start', 'services.stop', 'network.configure', 'startup.save']) expect(await app.count(command)).toBe(0)
  })
}
