import { test, expect } from './fixtures.mjs'

// Existing fictional peers only. These cases approve future startup but never
// restart the harness or change OS startup registration. Private values below
// are fictional, and no capture is attempted while private fields exist.
for (const locale of ['en', 'ja']) {
  test(`${locale}: save future outbound approval without starting, then cancel and disable it`, async ({ page, app }) => {
    const ja = locale === 'ja'
    await app.appearance(locale, ja ? 'dark' : 'light')
    await page.getByRole('button', { name: ja ? '保存済みサービス' : 'Saved services', exact: true }).click()
    const dialog = page.getByRole('dialog')
    await dialog.getByRole('button', { name: ja ? '接続定義を保存' : 'Save a connection', exact: true }).click()
    await dialog.getByLabel(ja ? '接続の名前' : 'Connection name', { exact: true }).fill('fixture-future-connection')
    await dialog.getByRole('combobox', { name: new RegExp(ja ? '保存するネットワーク' : 'Saved network') }).selectOption('tailnet')
    await dialog.getByRole('textbox', { name: new RegExp(ja ? '正確な端末 ID' : 'Exact device IDs') }).fill('fixture-studio')
    await dialog.getByLabel(ja ? 'ポート' : 'Ports', { exact: true }).fill('8080')
    await dialog.getByRole('button', { name: ja ? '停止状態の定義を確認' : 'Review stopped definition', exact: true }).click()
    await dialog.getByRole('button', { name: ja ? '確認した定義を保存' : 'Save reviewed definition', exact: true }).click()
    await dialog.getByRole('button', { name: ja ? 'すべて選択' : 'Select all', exact: true }).click()
    await dialog.getByText(ja ? '接続設定の補助' : 'Connection helpers', { exact: true }).click()
    await dialog.getByRole('button', { name: ja ? '自動開始の内容を確認' : 'Review automatic startup', exact: true }).click()
    await dialog.getByLabel(ja ? '起動許可の名前' : 'Startup approval name', { exact: true }).fill('fixture-future-startup')
    await dialog.getByRole('button', { name: ja ? '今後の起動内容を確認' : 'Review future startup', exact: true }).click()
    await expect(dialog).toContainText(ja ? '有限の有効期間は新たに始まります' : 'Each finite lifetime starts anew')
    await app.capture(`startup-approval-${locale}-desktop`)
    await dialog.getByRole('button', { name: ja ? '確認した今後の起動を許可' : 'Approve reviewed future startup', exact: true }).scrollIntoViewIfNeeded()
    await app.capture(`startup-approval-${locale}-actions`)
    await dialog.getByRole('button', { name: ja ? '選択に戻る' : 'Back to selection', exact: true }).click()
    expect(await app.count('startup.save')).toBe(0)
    await dialog.getByRole('button', { name: ja ? '今後の起動内容を確認' : 'Review future startup', exact: true }).click()
    await dialog.getByRole('button', { name: ja ? '確認した今後の起動を許可' : 'Approve reviewed future startup', exact: true }).click()
    await app.expectState(state => state.startup.entries.some(entry => entry.name === 'fixture-future-startup' && entry.enabled && entry.valid && entry.state === 'saved') && state.services.every(service => service.status === 'saved'))
    await dialog.getByRole('button', { name: ja ? '起動許可の無効化を確認' : 'Review disabling startup', exact: true }).click()
    await dialog.getByRole('button', { name: ja ? 'キャンセル' : 'Cancel', exact: true }).click()
    expect(await app.count('startup.disable')).toBe(0)
    await dialog.getByRole('button', { name: ja ? '起動許可の無効化を確認' : 'Review disabling startup', exact: true }).click()
    await dialog.getByRole('button', { name: ja ? '確認した起動許可を無効化' : 'Disable reviewed startup approval', exact: true }).click()
    await app.expectState(state => state.startup.entries.some(entry => entry.name === 'fixture-future-startup' && !entry.enabled))
    expect(await app.count('services.start')).toBe(0)
    expect(await app.count('service.connect')).toBe(0)
  })
}

test('saved fictional proxy credentials remain private through explicit save, reveal, hide and delete', async ({ page, app }) => {
  await page.locator('.app-header .header-actions button.icon-button').click()
  await page.getByRole('button', { name: 'Advanced connections', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('Proxy name', { exact: true }).fill('fixture-private-proxy')
  await dialog.getByLabel('Target device 1', { exact: true }).selectOption('fixture-studio')
  await dialog.getByLabel('Local proxy port', { exact: true }).fill(String(app.localServicePort))
  await dialog.getByRole('button', { name: 'Review exact scope', exact: true }).click()
  await dialog.getByRole('button', { name: 'Save this reviewed proxy', exact: true }).click()
  await expect(dialog.getByRole('checkbox', { name: 'Also approve this exact proxy on future online launches', exact: true })).not.toBeChecked()
  await dialog.getByRole('combobox', { name: 'Review private credential storage', exact: true }).selectOption('supplied')
  await dialog.getByLabel('Runtime username', { exact: true }).fill('fictional-stored-user')
  await dialog.getByLabel('Runtime password', { exact: true }).fill('fictional-stored-password')
  await dialog.getByRole('button', { name: 'Save entered credentials privately', exact: true }).click()
  await expect(dialog.locator('.proxy-credentials')).toHaveCount(0)
  await app.expectState(state => state.savedProxies.entries.some(entry => entry.name === 'fixture-private-proxy' && entry.credentialsSaved && !entry.startOnLaunch && !('username' in entry) && !('password' in entry)))
  expect(await app.count('proxy.reveal')).toBe(0)
  expect(await app.count('proxy.start')).toBe(0)
  expect(await app.count('proxy.saved.start')).toBe(0)
  await dialog.getByText('Saved proxy credentials', { exact: true }).click()
  await dialog.getByRole('button', { name: 'Manage saved proxies', exact: true }).click()
  await app.captureForm('saved-proxy-sanitized-list-desktop')
  await dialog.getByRole('button', { name: 'Reveal credentials temporarily', exact: true }).click()
  await expect.poll(() => dialog.locator('[data-private=proxy-credential]').evaluateAll(fields => fields.length === 2 && fields.every(field => field.value.length > 0)), { message: 'Only the explicit private view receives fixture credentials' }).toBe(true)
  await dialog.getByRole('button', { name: 'Hide and clear credentials', exact: true }).click()
  await expect(dialog.locator('[data-private=proxy-credential]')).toHaveCount(0)
  await page.setViewportSize({ width: 390, height: 844 })
  await app.captureForm('saved-proxy-cleared-list-390')
  await dialog.getByRole('button', { name: 'Review deleting saved credentials', exact: true }).click()
  await dialog.getByRole('button', { name: 'Cancel', exact: true }).click()
  expect(await app.count('proxy.saved.delete')).toBe(0)
  await dialog.getByRole('button', { name: 'Review deleting saved credentials', exact: true }).click()
  await dialog.getByRole('button', { name: 'Delete reviewed saved credentials', exact: true }).click()
  await app.expectState(state => state.savedProxies.entries.length === 0)
})
