import { test, expect, openDetailsSection } from './fixtures.mjs'

// Every test gets a fresh Studio process, authenticated context and private
// receiving root. Actions use the UI; state predicates observe the real Go app.
const studio = state => state.peers.find(peer => peer.name === 'Studio')
const pendingOutgoing = state => state.transfers.filter(transfer =>
  transfer.direction === 'outgoing' && ['offered', 'awaiting-acceptance'].includes(transfer.status))
const activeOutgoing = state => state.transfers.filter(transfer =>
  transfer.direction === 'outgoing' && ['offered', 'awaiting-acceptance', 'queued', 'transferring', 'saving'].includes(transfer.status))
const fileInput = page => page.locator('.conversation input[type=file]:not([webkitdirectory])')
const dialog = page => page.getByRole('dialog')
const serviceName = page => dialog(page).locator('input[required][maxlength="64"]')
const servicePorts = page => dialog(page).locator('input[aria-describedby="port-help"]')
const serviceLocalPort = page => dialog(page).locator('input[inputmode="numeric"]')
const serviceRow = (page, name) => page.locator('.service-rows > article').filter({
  has: page.locator('strong').filter({ hasText: new RegExp(`^${name}$`) }),
})

async function closeDialog(page) {
  await page.keyboard.press('Escape')
  await expect(dialog(page)).toHaveCount(0)
}

async function showDetails(page, app) {
  if (!await page.locator('.details-panel').isVisible()) await app.openDetails()
  await expect(page.locator('.details-panel')).toBeVisible()
}

async function openConnection(page) {
  await page.locator('.conversation-header').getByRole('button', { name: 'Connect to a service', exact: true }).click()
  await expect(dialog(page)).toBeVisible()
}

async function expectPrivateValue(locator, value, description) {
  // Assertions return only a boolean so a failure cannot print a private path.
  await expect.poll(() => locator.evaluate((element, expected) => element.value === expected, value), { message: description }).toBe(true)
}

async function uploads(page) {
  return page.evaluate(() => window.__sobaQA.uploads)
}

async function stageWithRequiredRetry(page, app, name, contents, captureFailure = false) {
  const source = await app.sourceFile(name, contents)
  await fileInput(page).setInputFiles(source)
  const preview = page.locator('.batch-preview')
  await expect(preview).toContainText(name)
  await preview.locator('.batch-footer .button-primary').click()

  // The real fixture fails the first staging request on every fresh instance.
  // Keep this explicit for each workflow that needs an actual pending offer.
  await expect(page.getByRole('alert')).toBeVisible()
  await expect(page.locator('.upload-progress')).toHaveCount(0)
  await expect(preview).toContainText(name)
  expect(await uploads(page), 'failed staging must not retry automatically').toBe(1)
  await app.expectState(state => pendingOutgoing(state).length === 0, 'failed staging creates no outgoing offer')
  if (captureFailure) await app.capture('upload-staging-failure-en-light-1440')

  await preview.locator('.batch-footer .button-primary').click()
  await expect(preview).toHaveCount(0)
  await app.expectState(state => pendingOutgoing(state).length === 1, 'manual retry creates one outgoing offer')
  expect(await uploads(page), 'one manual retry makes exactly two staging attempts').toBe(2)
  expect(await page.evaluate(() => {
    const qa = window.__sobaQA
    return qa.duplicateUploadIdentity && qa.uploadIDs.length === 2 && qa.uploadIDs[0] === qa.uploadIDs[1]
  }), 'retry must reuse the original upload identity').toBe(true)
}

test.beforeEach(async ({ app }) => {
  await app.appearance('en', 'light')
})

test('messages require an explicit send and recover from Enter, synthetic composition and UTF-8 validation', async ({ page, app }) => {
  await app.openPeer()
  const composer = page.locator('.composer textarea')
  const baseline = await app.count('message.send')
  await composer.fill('Fictional message draft')
  await composer.press('End')
  await composer.press('Enter')
  await expect(composer).toHaveValue('Fictional message draft\n')
  expect(await app.count('message.send'), 'plain Enter only inserts a newline').toBe(baseline)

  // Synthetic DOM composition is a regression check, not native IME acceptance.
  await composer.evaluate(element => {
    element.dispatchEvent(new CompositionEvent('compositionstart', { bubbles: true, data: 'あ' }))
    element.dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', code: 'Enter', ctrlKey: true, isComposing: true, bubbles: true }))
    element.dispatchEvent(new CompositionEvent('compositionend', { bubbles: true, data: 'あ' }))
  })
  expect(await app.count('message.send'), 'composition confirmation must not send').toBe(baseline)

  await composer.fill('あ'.repeat(5462))
  await page.getByRole('button', { name: 'Send message', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('displayed UTF-8 byte limit')
  await expect(composer).toHaveValue('あ'.repeat(5462))
  expect(await app.count('message.send'), 'oversized UTF-8 text stays local').toBe(baseline)

  await composer.fill('Fictional notes are ready for review.')
  await page.getByRole('button', { name: 'Send message', exact: true }).click()
  await expect(composer).toHaveValue('')
  await app.expectState(state => state.messages.some(message =>
    message.direction === 'outgoing' && message.text === 'Fictional notes are ready for review.' && message.status === 'sent'), 'explicit English send reaches the real peer')
  expect(await app.count('message.send')).toBe(baseline + 1)

  await composer.fill('Draft survives navigation')
  await page.getByRole('button', { name: 'Network graph', exact: true }).click()
  await expect(page.locator('.network-graph')).toBeVisible()
  await page.goBack()
  await expect(composer).toBeVisible()
  await expect(composer).toHaveValue('Draft survives navigation')
  await page.goForward()
  await expect(page.locator('.network-graph')).toBeVisible()
  await app.openPeer()
  await expect(composer).toHaveValue('Draft survives navigation')

  await app.appearance('ja', 'dark')
  await composer.fill('表示確認用の資料を共有します。内容を確認してください。')
  await page.getByRole('button', { name: 'メッセージを送信', exact: true }).click()
  await expect(composer).toHaveValue('')
  await app.expectState(state => state.messages.some(message =>
    message.direction === 'outgoing' && message.text === '表示確認用の資料を共有します。内容を確認してください。' && message.status === 'sent'), 'explicit Japanese send reaches the real peer')
  expect(await app.count('message.send')).toBe(baseline + 2)
})

test('incoming batch explicitly saves into the displayed default receiving directory', async ({ page, app }) => {
  await app.openPeer()
  const offer = page.locator('.transfer-card.incoming-offer')
  await expect(offer).toBeVisible()
  expect(await offer.locator('.accept-destination').evaluate((element, expected) => element.textContent.includes(expected), app.receiveDirectory)).toBe(true)
  await offer.getByRole('button', { name: 'Accept batch', exact: true }).click()
  await app.expectState(state => state.transfers.some(transfer => transfer.direction === 'incoming' && transfer.status === 'completed'), 'explicit acceptance saves the offered batch')
  await app.verifyReceived(app.receiveDirectory, 'design-notes.txt', 'Fictional design notes for browser acceptance.\n')
  expect(await app.count('transfer.accept')).toBe(1)
})

test('incoming batch retains its reviewed destination, resets to default and saves exact bytes without changing policy', async ({ page, app }) => {
  await app.openPeer()
  const offer = page.locator('.transfer-card.incoming-offer')
  await expect(offer).toBeVisible()
  const destination = await app.privateDirectory('reviewed-batches')
  const accepts = await app.count('transfer.accept')
  const settings = await app.count('settings.update')
  const policies = await app.count('peer.autosave')
  const destinationInput = offer.locator('.destination-field input')
  await offer.getByRole('button', { name: 'Change folder', exact: true }).click()
  await destinationInput.fill(destination)
  await page.getByRole('button', { name: 'Network graph', exact: true }).click()
  await page.goBack()
  await expect(destinationInput).toBeVisible()
  await expectPrivateValue(destinationInput, destination, 'navigation keeps the reviewed receiving folder')
  await offer.getByRole('button', { name: 'Use default folder', exact: true }).click()
  await expect(destinationInput).toHaveCount(0)
  expect(await offer.locator('.accept-destination').evaluate((element, expected) => element.textContent.includes(expected), app.receiveDirectory), 'default reset restores the configured receiving folder').toBe(true)

  await offer.getByRole('button', { name: 'Change folder', exact: true }).click()
  await destinationInput.fill(destination)
  await page.setViewportSize({ width: 1180, height: 960 })
  await app.capture('incoming-destination-en-light-1180')
  await app.appearance('ja', 'dark')
  await page.setViewportSize({ width: 390, height: 844 })
  await expectPrivateValue(destinationInput, destination, 'appearance changes keep the receiving folder draft')
  await app.capture('incoming-destination-ja-dark-390')
  expect(await app.count('transfer.accept'), 'editing a folder does not accept a batch').toBe(accepts)

  await offer.getByRole('button', { name: 'まとめて受信', exact: true }).click()
  await app.expectState(state => state.transfers.filter(transfer => transfer.direction === 'incoming' && transfer.status === 'completed').length === 1, 'one explicitly accepted batch finishes saving')
  expect(await app.count('transfer.accept')).toBe(accepts + 1)
  await app.verifyReceived(destination, 'design-notes.txt', 'Fictional design notes for browser acceptance.\n')
  expect(await app.count('settings.update'), 'per-batch folder does not edit preferences').toBe(settings)
  expect(await app.count('peer.autosave'), 'per-batch folder does not opt into automatic receiving').toBe(policies)
  await app.expectState(state => state.settings.receiveDirectory === app.receiveDirectory &&
    studio(state)?.autosave?.enabled === false && studio(state)?.autosave?.paused === false && !studio(state)?.autosave?.directory,
  'default directory and automatic receiving policy remain unchanged')
  const saved = page.locator('.transfer-card').filter({ has: page.locator('.transfer-top .badge', { hasText: /^保存済み$/ }) })
  await saved.locator('.file-details summary').click()
  await expect(saved.locator('.entry-path')).toHaveText('design-notes.txt')
  await saved.scrollIntoViewIfNeeded()
  await app.capture('incoming-saved-ja-dark-390')
})

test('file selection is additive and removing or cancelling a preview never stages a batch', async ({ page, app }) => {
  await app.openPeer()
  const first = await app.sourceFile('qa-notes.txt', 'Fictional browser acceptance notes.\n')
  const second = await app.sourceFile('qa-extra.txt', 'Second fictional attachment.\n')
  const preview = page.locator('.batch-preview')
  await fileInput(page).setInputFiles(first)
  await expect(preview).toContainText('qa-notes.txt')
  await fileInput(page).setInputFiles(second)
  await expect(preview).toContainText('qa-notes.txt')
  await expect(preview).toContainText('qa-extra.txt')
  await preview.getByRole('button', { name: 'Remove from batch: qa-extra.txt', exact: true }).click()
  await expect(preview).toContainText('qa-notes.txt')
  await expect(preview).not.toContainText('qa-extra.txt')
  expect(await uploads(page), 'selection and removal must stay local').toBe(0)
  await app.capture('upload-preview-en-light-1440')
  await preview.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(preview).toHaveCount(0)
  expect(await uploads(page), 'preview cancellation must not upload').toBe(0)
  await app.expectState(state => pendingOutgoing(state).length === 0, 'cancelled preview creates no outgoing transfer')
})

test('failed file staging preserves its draft and a manual same-ID retry creates one cancellable offer', async ({ page, app }) => {
  await app.openPeer()
  await stageWithRequiredRetry(page, app, 'retry-notes.txt', 'Fictional notes for staging recovery.\n', true)
  const cancellations = await app.count('transfer.cancel')
  await page.locator('.timeline-item.outgoing .transfer-actions').getByRole('button', { name: 'Cancel transfer', exact: true }).click()
  await app.expectState(state => state.transfers.filter(transfer => transfer.direction === 'outgoing' && transfer.status === 'cancelled').length === 1 && activeOutgoing(state).length === 0, 'explicit cancellation stops the single outgoing offer')
  expect(await app.count('transfer.cancel')).toBe(cancellations + 1)
})

test('preferences preserve locale and theme after reload and recover an invalid receiving directory in place', async ({ page, app }) => {
  await app.appearance('ja', 'dark')
  await page.reload()
  await expect(page.locator('.workspace')).toBeVisible()
  await expect(page.locator('html')).toHaveAttribute('lang', 'ja')
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await app.appearance('en', 'light')
  const trigger = page.getByRole('button', { name: 'Preferences', exact: true })
  await trigger.click()
  const directoryInput = dialog(page).getByRole('textbox', { name: 'Receive directory', exact: true })
  await expectPrivateValue(directoryInput, app.receiveDirectory, 'preferences start at the actual receiving root')
  await directoryInput.fill('relative/received')
  await dialog(page).getByRole('button', { name: 'Save', exact: true }).click()
  await expect(dialog(page).getByRole('alert')).toBeVisible()
  await expect(directoryInput).toHaveValue('relative/received')
  await app.expectState(state => state.settings.receiveDirectory === app.receiveDirectory, 'invalid directory leaves the saved preference unchanged')
  await directoryInput.fill(app.receiveDirectory)
  await dialog(page).getByRole('button', { name: 'Save', exact: true }).click()
  await expect(dialog(page).getByRole('status')).toContainText('Preferences saved')
  await app.expectState(state => state.settings.receiveDirectory === app.receiveDirectory, 'corrected directory is saved successfully')
  await closeDialog(page)
  await expect(trigger).toBeFocused()
})

test('revoking and allowing communication updates the real trust state and composer availability', async ({ page, app }) => {
  await app.openPeer()
  await app.openDetails()
  const details = page.locator('.details-panel')
  await details.getByRole('button', { name: 'Revoke permission', exact: true }).click()
  await app.expectState(state => studio(state)?.trusted === false, 'revoking permission updates the peer trust state')
  await expect(page.locator('.composer textarea')).toBeDisabled()
  await app.capture('permission-revoked-en-light-1440')
  await details.getByRole('button', { name: 'Allow communication', exact: true }).click()
  await app.expectState(state => studio(state)?.trusted === true, 'allowing communication restores peer trust')
  await app.closeDetails()
  await expect(page.locator('.composer textarea')).toBeEnabled()
})

test('automatic receiving reviews pause impact, retains a folder draft and resumes without resurrecting cancelled batches', async ({ page, app }) => {
  await app.openPeer()
  await app.openDetails()
  const details = page.locator('.details-panel')
  await details.getByRole('button', { name: 'Enable for this device', exact: true }).click()
  await expect(dialog(page).locator('.scope-note')).toBeVisible()
  await dialog(page).getByRole('button', { name: 'Enable for this device', exact: true }).click()
  await app.expectState(state => studio(state)?.autosave?.enabled === true && !studio(state)?.autosave?.paused, 'automatic receiving is explicitly enabled for the selected peer')
  await expect(dialog(page)).toHaveCount(0)
  await app.closeDetails()

  await stageWithRequiredRetry(page, app, 'pause-review.txt', 'Fictional batch for pause review.\n')
  await app.openDetails()
  const pause = details.getByRole('button', { name: 'Pause messages and files', exact: true })
  await pause.click()
  await expect(dialog(page)).toContainText('Original files stay in place')
  await expect(dialog(page).locator('.pause-affected')).toContainText('Outgoing batches affected: 1')
  await app.capture('autosave-pause-review-en-light-1440')
  const policiesBeforeCancel = await app.count('peer.autosave')
  await dialog(page).getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(dialog(page)).toHaveCount(0)
  expect(await app.count('peer.autosave'), 'cancelled pause review sends no policy change').toBe(policiesBeforeCancel)
  await app.expectState(state => !studio(state)?.autosave?.paused && pendingOutgoing(state).length === 1, 'cancelling the pause leaves the pending batch active')

  await pause.click()
  await dialog(page).getByRole('button', { name: 'Pause messages and files', exact: true }).click()
  await app.expectState(state => studio(state)?.autosave?.paused === true && activeOutgoing(state).length === 0 &&
    state.transfers.some(transfer => transfer.direction === 'outgoing' && transfer.status === 'cancelled'), 'confirmed pause cancels outgoing work and pauses the peer')
  await expect(dialog(page)).toHaveCount(0)
  await expect(page.locator('.composer textarea')).toBeDisabled()

  const folder = await app.privateDirectory('automatic-receiving')
  const edits = await app.count('peer.autosave')
  await details.getByRole('button', { name: 'Edit folder', exact: true }).click()
  await dialog(page).locator('form input').fill(folder)
  await closeDialog(page)
  expect(await app.count('peer.autosave'), 'closing a folder draft leaves its policy unchanged').toBe(edits)
  await app.expectState(state => studio(state)?.autosave?.enabled === true && studio(state)?.autosave?.paused === true &&
    studio(state)?.autosave?.directory === app.receiveDirectory, 'closing the draft preserves enabled, paused and folder values')
  await details.getByRole('button', { name: 'Edit folder', exact: true }).click()
  await expectPrivateValue(dialog(page).locator('form input'), folder, 'reopening retains the automatic receiving folder draft')
  await page.setViewportSize({ width: 1180, height: 960 })
  await app.capture('autosave-folder-en-light-1180')
  await closeDialog(page)
  await app.appearance('ja', 'dark')
  await details.getByRole('button', { name: 'フォルダーを変更', exact: true }).click()
  await expectPrivateValue(dialog(page).locator('form input'), folder, 'language changes preserve the folder draft')
  await page.setViewportSize({ width: 390, height: 844 })
  await app.capture('autosave-folder-ja-dark-390')
  await dialog(page).locator('button[type=submit]').click()
  await app.expectState(state => studio(state)?.autosave?.enabled === true && studio(state)?.autosave?.paused === true &&
    studio(state)?.autosave?.directory === folder && state.settings.receiveDirectory === app.receiveDirectory,
  'saving the folder changes only that peer directory while keeping enabled and paused state')
  await expect(dialog(page)).toHaveCount(0)
  expect(await app.count('peer.autosave')).toBe(edits + 1)

  await page.setViewportSize({ width: 1440, height: 960 })
  await app.appearance('en', 'light')
  await details.getByRole('button', { name: 'Resume messages and files', exact: true }).click()
  await app.expectState(state => studio(state)?.autosave?.paused === false && studio(state)?.autosave?.directory === folder && activeOutgoing(state).length === 0,
    'resuming preserves the reviewed directory and does not restart cancelled batches')
  await expect(page.locator('.composer textarea')).toBeEnabled()
  await details.getByRole('button', { name: 'Turn off', exact: true }).click()
  await app.expectState(state => studio(state)?.autosave?.enabled === false && studio(state)?.autosave?.directory === folder,
    'turning off automatic receiving preserves the chosen directory')
})

test('manual service validation offers correction and Escape restores its trigger without starting a listener', async ({ page, app }) => {
  await app.openPeer()
  const starts = await app.count('service.connect')
  await openConnection(page)
  await serviceName(page).fill('reviewed-service')
  await servicePorts(page).fill('8000-8064')
  await expect(dialog(page).locator('button[type=submit]')).toBeDisabled()
  await app.captureForm('service-invalid-range-en-light-1440')
  await servicePorts(page).fill('0,65536')
  await expect(dialog(page).locator('button[type=submit]')).toBeDisabled()
  await servicePorts(page).fill('8080')
  await expect(dialog(page).locator('button[type=submit]')).toBeEnabled()
  await expect(dialog(page).locator('.service-preview')).toContainText('127.0.0.1:8080')
  await app.captureForm('service-validation-en-light-1440')
  await closeDialog(page)
  await expect(page.locator('.conversation-header .connect-header')).toBeFocused()
  expect(await app.count('service.connect')).toBe(starts)
  await app.expectState(state => !state.services.some(service => service.name === 'reviewed-service'), 'closing validation does not create a service')
})

test('manual service starts and stops, copies authoritative settings and restarts only after review', async ({ page, app }) => {
  await app.openPeer()
  await openConnection(page)
  await serviceName(page).fill('reviewed-service')
  await servicePorts(page).fill('8080')
  await serviceLocalPort(page).fill(String(app.localServicePort))
  await dialog(page).locator('button[type=submit]').click()
  await app.expectState(state => state.services.some(service => service.name === 'reviewed-service' && service.status === 'active' &&
    service.network === 'tcp' && service.ports === '8080' && service.localPort === app.localServicePort), 'reviewed service starts with the chosen local listener')
  await expect(dialog(page)).toHaveCount(0)
  await showDetails(page, app)
  const row = serviceRow(page, 'reviewed-service')
  await expect(row).toBeVisible()
  await app.capture('service-active-en-light-1440')
  await row.getByRole('button', { name: 'Stop', exact: true }).click()
  await app.expectState(state => !state.services.some(service => service.name === 'reviewed-service' && service.status === 'active'), 'stopping the service removes its active listener')

  const reads = await app.count('service.config')
  const starts = await app.count('service.connect')
  await openDetailsSection(row.locator('.service-tools'))
  await row.getByRole('button', { name: 'Copy settings', exact: true }).click()
  await expect(serviceName(page)).toHaveValue('reviewed-service-2')
  expect(await app.count('service.config')).toBe(reads + 1)
  expect(await app.count('service.connect'), 'reading saved settings cannot start a listener').toBe(starts)
  await serviceName(page).fill('reviewed-copy-draft')
  await closeDialog(page)
  await openDetailsSection(row.locator('.service-tools'))
  await row.getByRole('button', { name: 'Copy settings', exact: true }).click()
  await expect(serviceName(page)).toHaveValue('reviewed-copy-draft')
  await closeDialog(page)
  await openDetailsSection(row.locator('.service-tools'))
  await row.getByRole('button', { name: 'Edit and start', exact: true }).click()
  await expect(serviceName(page)).toHaveValue('reviewed-service')
  await expect(servicePorts(page)).toHaveValue('8080')
  await expect(serviceLocalPort(page)).toHaveValue(String(app.localServicePort))
  await app.captureForm('service-restart-review-en-light-1440')
  expect(await app.count('service.connect'), 'review itself must not restart the saved listener').toBe(starts)
  await dialog(page).getByRole('button', { name: 'Apply and start', exact: true }).click()
  await app.expectState(state => state.services.some(service => service.name === 'reviewed-service' && service.status === 'active'), 'applying the reviewed edit restarts the listener')
  await expect(dialog(page)).toHaveCount(0)
  expect(await app.count('service.connect')).toBe(starts + 1)
  await row.getByRole('button', { name: 'Stop', exact: true }).click()
  await app.expectState(state => !state.services.some(service => service.name === 'reviewed-service' && service.status === 'active'), 'the restarted listener can be explicitly stopped')
})

test('advertised service selection locks its target and starts one reviewed listener with copyable identity', async ({ page, app }) => {
  await app.openPeer()
  await app.openDetails()
  await page.locator('.details-panel').getByRole('button', { name: 'Check shared services', exact: true }).click()
  await app.expectState(state => state.availableServices.some(service => service.peerId === studio(state)?.id && service.network === 'tcp' && service.ports === '8080' && service.purpose === 'web' && typeof service.revision === 'string' && service.revision.length > 0 && Number.isFinite(Date.parse(service.checkedAt)) && service.lifetime === 'finite' && Number.isFinite(Date.parse(service.expiresAt))), 'Core discovery returns fresh immutable review metadata for its actual share')
  await app.closeDetails()
  const starts = await app.count('service.connect')
  await openConnection(page)
  const selection = dialog(page).getByRole('combobox', { name: 'Available services', exact: true })
  const advertised = selection.getByRole('option').filter({ hasText: /TCP 8080/ })
  await expect(advertised).toHaveCount(1)
  // This non-secret fixture identity is used only in memory, never in reports.
  const advertisedID = await advertised.getAttribute('value')
  expect(Boolean(advertisedID), 'the advertised option has a stable identity').toBe(true)
  await selection.selectOption(advertisedID)
  await serviceName(page).fill('advertised-service')
  await serviceLocalPort(page).fill(String(app.localServicePort))
  await expect(servicePorts(page)).toHaveValue('8080')
  await expect(servicePorts(page)).toBeDisabled()
  await expect(dialog(page).locator('.protocol-field select')).toHaveValue('tcp')
  await expect(dialog(page).locator('.protocol-field select')).toBeDisabled()
  await expect(dialog(page).locator('.service-preview')).toContainText(`127.0.0.1:${app.localServicePort}`)
  expect(await app.count('service.connect'), 'selecting an advertisement does not start a listener').toBe(starts)
  await page.setViewportSize({ width: 1180, height: 960 })
  await app.captureForm('service-advertised-en-light-1180')
  const refreshes = await app.count('discovery.refresh')
  await dialog(page).locator('button[type=submit]').click()
  await app.expectState(state => state.services.some(service => service.name === 'advertised-service' && service.status === 'active' &&
    service.network === 'tcp' && service.ports === '8080' && service.localPort === app.localServicePort), 'advertised connection starts at the exact reviewed target and local port')
  await expect(dialog(page)).toHaveCount(0)
  expect(await app.count('service.connect')).toBe(starts + 1)
  expect(await app.count('discovery.refresh')).toBe(refreshes + 1)
  await showDetails(page, app)
  const row = serviceRow(page, 'advertised-service')
  const reads = await app.count('service.config')
  await openDetailsSection(row.locator('.service-tools'))
  await row.getByRole('button', { name: 'Copy settings', exact: true }).click()
  await expect(serviceName(page)).toHaveValue('advertised-service-2')
  await expectPrivateValue(selection, advertisedID, 'authoritative settings retain the advertised service identity')
  expect(await app.count('service.config')).toBe(reads + 1)
  await dialog(page).getByText('More options', { exact: true }).click()
  await expect(dialog(page).getByRole('combobox', { name: 'Purpose', exact: true })).toHaveValue('web')
  await expect(dialog(page).getByRole('combobox', { name: 'Purpose', exact: true })).toBeDisabled()
  await closeDialog(page)
  expect(await app.count('service.connect'), 'copy inspection does not restart or duplicate a connection').toBe(starts + 1)
  await row.getByRole('button', { name: 'Stop', exact: true }).click()
  await app.expectState(state => !state.services.some(service => service.name === 'advertised-service' && service.status === 'active'), 'the advertised listener stops explicitly')
})

test('scoped sharing retains a bilingual review draft and copies its exact ports, exclusions and recipient scope', async ({ page, app }) => {
  await app.openPeer()
  await app.openDetails()
  const details = page.locator('.details-panel')
  const starts = await app.count('service.share')
  await details.getByRole('button', { name: 'Share a service', exact: true }).click()
  await serviceName(page).fill('reviewed-share')
  await servicePorts(page).fill('8081')
  await expect(dialog(page).locator('.peer-checkboxes input:checked')).toHaveCount(1)
  await expect(dialog(page).locator('.peer-checkboxes')).toContainText('Studio')
  await expect(dialog(page).locator('.peer-checkboxes').getByRole('checkbox', { name: /Studio/ })).toBeChecked()
  await expect(dialog(page).locator('.advanced input:not([type=checkbox])')).toHaveValue('54543-54545')
  await expect(dialog(page).locator('.advanced input[type=checkbox]')).not.toBeChecked()
  await page.setViewportSize({ width: 1180, height: 960 })
  await app.captureForm('service-share-en-light-1180')
  await closeDialog(page)
  expect(await app.count('service.share'), 'closing a share review creates no inbound rule').toBe(starts)
  await app.appearance('ja', 'dark')
  await details.getByRole('button', { name: 'サービスを共有', exact: true }).click()
  await expect(serviceName(page)).toHaveValue('reviewed-share')
  await expect(servicePorts(page)).toHaveValue('8081')
  await page.setViewportSize({ width: 390, height: 844 })
  await app.captureForm('service-share-ja-dark-390')
  await dialog(page).locator('button[type=submit]').click()
  await app.expectState(state => state.shares.some(service => service.name === 'reviewed-share' && service.status === 'active' &&
    service.network === 'tcp' && service.ports === '8081' && service.peerIds.length === 1 && service.peerIds[0] === studio(state)?.id),
  'reviewed sharing opens only the selected port for the selected peer')
  await expect(dialog(page)).toHaveCount(0)
  expect(await app.count('service.share')).toBe(starts + 1)

  await page.setViewportSize({ width: 1440, height: 960 })
  await app.appearance('en', 'light')
  await showDetails(page, app)
  const row = serviceRow(page, 'reviewed-share')
  const reads = await app.count('service.config')
  await openDetailsSection(row.locator('.service-tools'))
  await row.getByRole('button', { name: 'Copy settings', exact: true }).click()
  await expect(serviceName(page)).toHaveValue('reviewed-share-2')
  await expect(servicePorts(page)).toHaveValue('8081')
  await expect(dialog(page).locator('.advanced input:not([type=checkbox])')).toHaveValue('54543-54545')
  await expect(dialog(page).locator('.advanced input[type=checkbox]')).not.toBeChecked()
  await expect(dialog(page).locator('.peer-checkboxes input:checked')).toHaveCount(1)
  await expect(dialog(page).locator('.peer-checkboxes').getByRole('checkbox', { name: /Studio/ })).toBeChecked()
  expect(await app.count('service.config')).toBe(reads + 1)
  await closeDialog(page)
  expect(await app.count('service.share'), 'reading saved scope does not create another permission').toBe(starts + 1)
  await row.getByRole('button', { name: 'Stop', exact: true }).click()
  await app.expectState(state => !state.shares.some(service => service.name === 'reviewed-share' && service.status === 'active'), 'explicit stop removes the scoped sharing rule')
})

test('device services open first and direct file and message actions preserve drafts', async ({ page, app }) => {
  await page.locator('.device-row').first().click()
  await expect(page.getByRole('region', { name: 'Services and connection' })).toBeVisible()
  await expect(page.locator('.composer textarea')).toBeHidden()
  await expect(page.getByRole('button', { name: 'Connect to a service', exact: true })).toBeEnabled()
  const chooser = page.waitForEvent('filechooser')
  await page.getByRole('button', { name: 'Send files', exact: true }).click()
  await (await chooser).setFiles({ name: 'review-notes.txt', mimeType: 'text/plain', buffer: Buffer.from('Fictional notes for review.\n') })
  await expect(page.locator('.batch-preview')).toContainText('review-notes.txt')
  expect(await uploads(page), 'choosing a file only creates a local review draft').toBe(0)
  await page.locator('.device-sections').getByRole('button', { name: 'Services', exact: true }).click()
  await page.getByRole('button', { name: 'Write a message', exact: true }).click()
  await expect(page.locator('.batch-preview')).toContainText('review-notes.txt')
  await page.locator('.composer textarea').fill('Fictional unsent message')
  await page.locator('.device-sections').getByRole('button', { name: 'Services', exact: true }).click()
  await page.getByRole('button', { name: 'Network graph', exact: true }).click()
  await page.goBack()
  await expect(page.getByRole('region', { name: 'Services and connection' })).toBeVisible()
  await page.getByRole('button', { name: 'Files & messages', exact: true }).click()
  await expect(page.locator('.composer textarea')).toHaveValue('Fictional unsent message')
  await expect(page.locator('.batch-preview')).toContainText('review-notes.txt')
  expect(await app.count('message.send')).toBe(0)
})

test('capacity changes preserve history until a separate reviewed cleanup', async ({ page, app }) => {
  await page.getByRole('button', { name: 'Preferences', exact: true }).click()
  await page.getByRole('button', { name: 'Capacity and history', exact: true }).click()
  await expect(dialog(page).getByText('Files and messages', { exact: true })).toBeVisible()
  await dialog(page).locator('summary').filter({ hasText: /^Message history$/ }).click()
  await page.getByRole('combobox', { name: 'Messages to retain', exact: true }).selectOption('limited')
  await page.getByRole('spinbutton', { name: 'Messages to retain: Limit', exact: true }).fill('1')
  await page.getByRole('button', { name: 'Review changes', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Apply reviewed settings', exact: true })).toBeVisible()
  expect(await app.count('policy.apply')).toBe(0)
  expect(await app.count('message.history.cleanup')).toBe(0)
  await page.getByRole('button', { name: 'Apply reviewed settings', exact: true }).click()
  await expect(page.getByText('Capacity settings saved', { exact: true })).toBeVisible()
  await app.expectState(state => state.messages.length === 2, 'saving retention settings keeps both fixture messages')
  await page.getByRole('button', { name: 'Review history cleanup', exact: true }).click()
  const review = page.getByLabel('Review permanent removal', { exact: true })
  await expect(review).toContainText('Messages to remove1')
  await expect(review).toContainText('Messages to keep1')
  await expect(review).toContainText('cannot be undone')
  await review.getByRole('button', { name: 'Cancel', exact: true }).click()
  expect(await app.count('message.history.cleanup')).toBe(0)
  await app.expectState(state => state.messages.length === 2, 'cancelling cleanup keeps both messages')
  await page.getByRole('button', { name: 'Review history cleanup', exact: true }).click()
  await page.getByRole('button', { name: 'Permanently remove reviewed messages', exact: true }).click()
  await expect(page.getByText('Reviewed message history removed', { exact: true })).toBeVisible()
  await app.expectState(state => state.messages.length === 1, 'only the separately reviewed cleanup removes history')
  expect(await app.count('policy.apply')).toBe(1)
  expect(await app.count('message.history.cleanup')).toBe(1)
})

test('saved definitions open no listener and removal requires a separate review', async ({ page, app }) => {
  await app.openPeer()
  await openConnection(page)
  await serviceName(page).fill('saved-example')
  await servicePorts(page).fill('8020')
  await dialog(page).getByRole('button', { name: 'Save without starting', exact: true }).click()
  await expect(dialog(page)).toHaveCount(0)
  await app.expectState(state => state.services.some(service => service.name === 'saved-example' && service.status === 'saved'), 'saving persists a stopped definition')
  expect(await app.count('service.connect')).toBe(0)
  expect(await app.count('service.save')).toBe(1)
  await showDetails(page, app)
  const row = serviceRow(page, 'saved-example')
  await openDetailsSection(row.locator('.service-tools'))
  await row.getByRole('button', { name: 'Remove saved rule', exact: true }).click()
  await expect(dialog(page).getByRole('button', { name: 'Remove reviewed rule', exact: true })).toBeEnabled()
  await closeDialog(page)
  expect(await app.count('service.delete')).toBe(0)
  await openDetailsSection(row.locator('.service-tools'))
  await row.getByRole('button', { name: 'Remove saved rule', exact: true }).click()
  await dialog(page).getByRole('button', { name: 'Remove reviewed rule', exact: true }).click()
  await app.expectState(state => !state.services.some(service => service.name === 'saved-example'), 'explicit reviewed deletion removes only the saved fixture definition')
  expect(await app.count('service.delete')).toBe(1)
})

test('saved groups review start and stop, then import a private definitions export as stopped settings', async ({ page, app }) => {
  await app.openPeer()
  await openConnection(page)
  await serviceName(page).fill('group-example')
  await servicePorts(page).fill('8080')
  await serviceLocalPort(page).fill(String(app.localServicePort))
  await dialog(page).getByRole('button', { name: 'Save without starting', exact: true }).click()
  await expect(dialog(page)).toHaveCount(0)
  await app.closeDetails()
  await page.getByRole('button', { name: 'Saved services', exact: true }).click()
  await dialog(page).getByRole('checkbox', { name: /group-example/ }).check()
  await dialog(page).getByText('Save this selection as a group', { exact: true }).click()
  await dialog(page).getByRole('textbox', { name: 'Group name', exact: true }).fill('reviewed-tools')
  await dialog(page).getByRole('button', { name: 'Save group', exact: true }).click()
  await expect(page.getByText('Group saved without starting services', { exact: true })).toBeVisible()
  expect(await app.count('services.start')).toBe(0)
  await dialog(page).getByRole('combobox', { name: 'Saved group', exact: true }).selectOption('reviewed-tools')
  await dialog(page).getByRole('button', { name: 'Review start', exact: true }).click()
  const scope = page.getByRole('region', { name: 'Review selected services', exact: true })
  await expect(scope).toContainText('group-example')
  await expect(scope).toContainText('Until stopped')
  await expect(scope).toContainText(`127.0.0.1:${app.localServicePort} → 8080`)
  await scope.getByRole('button', { name: 'Start reviewed services', exact: true }).click()
  await app.expectState(state => state.services.some(service => service.name === 'group-example' && service.status === 'active'), 'the reviewed saved group establishes a listener')
  await dialog(page).getByRole('button', { name: 'Review stop', exact: true }).click()
  await scope.getByRole('button', { name: 'Stop reviewed services', exact: true }).click()
  await app.expectState(state => state.services.some(service => service.name === 'group-example' && service.status === 'stopped'), 'reviewed group stop closes the listener and retains its definition')
  await dialog(page).getByText('Import and export', { exact: true }).click()
  const downloaded = page.waitForEvent('download')
  await dialog(page).getByRole('button', { name: 'Download saved definitions', exact: true }).click()
  const file = await downloaded
  expect(file.suggestedFilename()).toBe('sobalink-services.json')
  await dialog(page).getByLabel('Choose a definitions file', { exact: true }).setInputFiles(await file.path())
  await dialog(page).getByRole('button', { name: 'Review import', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Review replacement', exact: true })).toContainText('reviewed-tools')
  expect(await app.count('profile.import')).toBe(0)
  await page.getByRole('button', { name: 'Replace with reviewed definitions', exact: true }).click()
  await expect(page.getByText('Definitions imported in the stopped state', { exact: true })).toBeVisible()
  await app.expectState(state => state.services.some(service => service.name === 'group-example' && service.status === 'saved'), 'import restores definitions without starting listeners')
  expect(await app.count('services.start')).toBe(1)
  expect(await app.count('profile.import')).toBe(1)
})


test('real Core discovery rejects altered advertised scope without creating a listener', async ({ page, app }) => {
  await app.openPeer('services')
  await app.openDetails()
  await page.getByRole('button', { name: 'Check shared services', exact: true }).click()
  await app.expectState(state => state.availableServices.some(service => service.peerId === 'fixture-studio' && service.purpose === 'web' && service.revision && service.checkedAt))
  // Only fictional metadata stays in page memory. The result deliberately
  // contains booleans/codes, never the local session or request credential.
  for (const change of ['purpose', 'ports', 'grant']) {
    const outcome = await page.evaluate(async ({ change, localPort }) => {
      const state = await (await fetch('/api/state')).json()
      const advertised = state.availableServices.find(service => service.peerId === 'fixture-studio' && service.network === 'tcp' && service.ports === '8080')
      if (!advertised?.revision || !advertised.checkedAt) return { metadata: false }
      const payload = { name: 'rejected-advertised-change', backend: 'tailnet', peerId: advertised.peerId, serviceId: advertised.id, serviceRevision: advertised.revision, network: advertised.network, ports: advertised.ports, purpose: advertised.purpose, localPort, loopbackHost: '127.0.0.1', lifetime: 'until-stopped', ttlSeconds: 0, discoverable: false }
      if (change === 'purpose') payload.purpose = 'ssh'
      if (change === 'ports') payload.ports = '8081'
      if (change === 'grant') payload.serviceId = 'fictional-replaced-grant'
      const response = await fetch('/api/command', { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-CSRF-Token': state.csrfToken }, body: JSON.stringify({ requestId: crypto.randomUUID(), name: 'service.connect', payload }) })
      const body = await response.json()
      return { metadata: true, refused: !response.ok, code: body.code }
    }, { change, localPort: app.localServicePort })
    expect(outcome).toEqual({ metadata: true, refused: true, code: 'discovery_review_changed' })
  }
  await app.expectState(state => !state.services.some(service => service.name === 'rejected-advertised-change'))
})
