import { describe, expect, it, vi } from 'vitest'
import { ResourceAttemptRegistry, MAX_SHARED_ATTEMPTS } from './attempt-registry'
import { ResourceSettingsController } from './controller'
import { applied, context, deferred, remotePreview, remoteReply, remoteSelection, response, selectRemote } from './fixtures.test-support'
const claim = { peerKey: remoteSelection.peerKey, resourceId: remoteSelection.selector.target.resourceId, operationId: remotePreview.operationId }
const groupId = '9'.repeat(32), groupOwner = `group:${groupId}`
const terminal = { operationId: claim.operationId, outcome: applied, evidenceDurable: true }
function single(registry: ResourceAttemptRegistry, handler = response) { const calls: Parameters<typeof response>[0][] = []; const controller = new ResourceSettingsController((name, payload, signal) => { const call = { name, payload, signal }; calls.push(call); return Promise.resolve(handler(call)) }, () => {}, Date.now, registry); controller.updateContext(context); controller.open(); return { controller, calls } }
describe('shared single and group uncertainty registry', () => {
  it('reserves every scope atomically before any listener notification', () => { const registry = new ResourceAttemptRegistry(), notify = vi.fn(); registry.subscribe(notify); expect(registry.reserveNew(groupOwner, [claim, { ...claim, peerKey: '8'.repeat(64) }])).toBe(true); expect(notify).not.toHaveBeenCalled(); expect(registry.blocked(claim)).toBe(true); expect(registry.reserveNew('single:another', [claim])).toBe(false); registry.emit(); expect(notify).toHaveBeenCalledOnce() })
  it('rejects an entire conflicting selection without retaining a partial new claim', () => { const registry = new ResourceAttemptRegistry(); registry.reserveNew('single:first', [claim]); const other = { ...claim, peerKey: '8'.repeat(64) }; expect(registry.reserveNew(groupOwner, [other, claim])).toBe(false); expect(registry.blocked(other)).toBe(false) })
  it('keeps owner namespaces separate and never settles another attempt from a reused operation token', () => { const registry = new ResourceAttemptRegistry(); registry.reserveNew('single:first', [claim]); registry.retainHistory(groupOwner, [claim]); expect(registry.settleTarget('single:first', claim, terminal)).toBe(true); expect(registry.blocked(claim)).toBe(true); expect(registry.settleTarget('single:wrong', claim, terminal)).toBe(false); expect(registry.settleTarget(groupOwner, claim, terminal)).toBe(true); expect(registry.blocked(claim)).toBe(false) })
  it('never releases on unavailable unknown nondurable wrong-operation or wrong-scope evidence', () => { const registry = new ResourceAttemptRegistry(); registry.reserveNew(groupOwner, [claim]); expect(registry.settleTarget(groupOwner, claim, { ...terminal, evidenceDurable: false })).toBe(false); expect(registry.settleTarget(groupOwner, claim, { ...terminal, operationId: '8'.repeat(64) })).toBe(false); expect(registry.settleTarget(groupOwner, { ...claim, resourceId: '8'.repeat(32) }, terminal)).toBe(false); expect(registry.blocked(claim)).toBe(true) })
  it('requires durable idle stopped local evidence before releasing a known unsent group member', () => { const registry = new ResourceAttemptRegistry(); registry.reserveNew(groupOwner, [claim]); const proof = { runId: groupId, activity: 'idle', admissionFinished: true, dispatch: 'not_attempted', admissionStop: 'user_canceled', localDurability: 'durable', rowLocalDurability: 'durable' }; expect(registry.settleGroupNonDispatch(groupOwner, claim, { ...proof, activity: 'applying' })).toBe(false); expect(registry.settleGroupNonDispatch(groupOwner, claim, { ...proof, admissionStop: 'none' })).toBe(false); expect(registry.settleGroupNonDispatch(groupOwner, claim, { ...proof, localDurability: 'uncertain' })).toBe(false); expect(registry.settleGroupNonDispatch(groupOwner, claim, proof)).toBe(true) })
  it('retains bounded tombstones without eviction or same-owner readmission', () => { const registry = new ResourceAttemptRegistry(); for (let i = 0; i < MAX_SHARED_ATTEMPTS; ++i) { const owner = `single:${i}`, next = { ...claim, peerKey: i.toString(16).padStart(64, '0') }; expect(registry.reserveNew(owner, [next])).toBe(true); registry.settleTarget(owner, next, terminal) }; expect(registry.full).toBe(true); expect(registry.reserveNew('single:new', [claim])).toBe(false); expect(registry.reserveNew('single:0', [claim])).toBe(false) })
  it('blocks W1 preview and apply across grant auth process and dialog changes while allowing inspection', async () => { const registry = new ResourceAttemptRegistry(), h = single(registry); registry.reserveNew(groupOwner, [claim]); registry.emit(); h.controller.updateContext({ ...context, selectionRevision: 'new-auth-and-pair', processId: 999 }); h.controller.close(); h.controller.open(); h.controller.select({ ...remoteSelection, selector: { ...remoteSelection.selector, grantId: '8'.repeat(32), grantRevision: 9 } }); await h.controller.inspect(); await h.controller.preview(); await h.controller.confirmApply(); expect(h.calls.map(call => call.name)).toEqual(['resource.remote.management.inspect']); expect(h.controller.getSnapshot().blocked).toBe(true) })
  it('a W1 attempted apply blocks group claims before its transport runs', async () => { const registry = new ResourceAttemptRegistry(), pending = deferred(); const calls: string[] = []; const controller = new ResourceSettingsController((name, payload, signal) => { calls.push(name); if (name === 'resource.remote.management.apply') { expect(registry.reserveNew(groupOwner, [claim])).toBe(false); return pending.promise }; return Promise.resolve(response({ name, payload, signal })) }, () => {}, Date.now, registry); controller.updateContext(context); controller.open(); await selectRemote(controller); await controller.preview(); const apply = controller.confirmApply(); controller.stopWaiting(); pending.resolve(remoteReply('apply')); await apply; expect(registry.blocked(claim)).toBe(true); expect(calls.filter(name => name.endsWith('.apply'))).toHaveLength(1) })
  it('a reentrant registry subscriber cannot send a consumed W1 apply after closing its owner', async () => { const registry = new ResourceAttemptRegistry(), h = single(registry); await selectRemote(h.controller); await h.controller.preview(); registry.subscribe(() => h.controller.close()); await h.controller.confirmApply(); expect(h.calls.some(call => call.name.endsWith('.apply'))).toBe(false); expect(registry.blocked(claim)).toBe(true) })
  it('clears the matching W1 shared claim only after exact durable terminal status', async () => { const registry = new ResourceAttemptRegistry(), pending = deferred(); const controller = new ResourceSettingsController((name, payload, signal) => name === 'resource.remote.management.apply' ? pending.promise : Promise.resolve(response({ name, payload, signal })), () => {}, Date.now, registry); controller.updateContext(context); controller.open(); await selectRemote(controller); await controller.preview(); const apply = controller.confirmApply(); controller.stopWaiting(); pending.resolve(remoteReply('apply')); await apply; expect(registry.blocked(claim)).toBe(true); await controller.checkStatus(controller.getSnapshot().attempts[0].attemptId); expect(registry.blocked(claim)).toBe(false) })
})
