package main

// No inline scripts, external resources, URL credentials, browser storage, or
// HTML interpolation of peer-controlled strings. Reviews use textContent only.
const handoffHTML = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sobalink local restart</title></head><body><main><h1 id="title">Sobalink</h1><p id="message">Waiting for the reviewed request / 確認済みの要求を待っています</p><pre id="review"></pre><button id="continue" hidden></button><button id="cancel" hidden></button><p><input id="management" hidden readonly aria-label="Local management URL"></p><button id="open" hidden></button><p id="code"></p></main><script src="/bridge.js"></script></body></html>`

const handoffJS = `
'use strict';
const parentWindow=window.opener;
let token='', received=false, pending=false, stopped=false, polling, expiry;
const el=id=>document.getElementById(id);
const words={en:{title:'Restart reviewed local management',review:'Review the same peer, endpoints, scope and original deadline below. Connections will stop briefly. The successor starts offline and rechecks this exact review. Enter its fresh code in the normal login screen; no session is transferred.',continue:'Confirm restart and continue',cancel:'Cancel this attempt',working:'Restart requested. Waiting for verified shutdown and a fresh offline successor. Closing this page requests cancellation; an already completed operation cannot be undone.',ready:'Fresh management is available. Use Open to launch it through this device, then enter the one-time code below. If it does not open, copy the address into your browser address bar. Pair, network, listener and application readiness are separate; check progress there.',open:'Open fresh local management',manual:'Copy the address below into your browser address bar and enter the one-time code. Automatic opening was unavailable or uncertain.',code:'Fresh one-time code: ',failed:'Continuation is uncertain or unavailable. No automatic retry. Inspect the current local management state before reviewing again.',cancelled:'Cancellation requested. Already saved confirmation is not undone.',expired:'The original review expired. Review again from current local management.'},ja:{title:'確認済みのローカル管理を再起動',review:'同じ相手、エンドポイント、対象範囲、元の期限を確認してください。接続が一時停止します。後継はオフラインで起動し、この確認内容を再検証します。通常のログイン画面に新しいコードを入力してください。セッションは移行しません。',continue:'再起動を確認して続ける',cancel:'この試行を中止',working:'再起動を要求しました。停止完了と新しいオフラインの後継を確認しています。この画面を閉じると中止を要求します。完了済みの操作は取り消せません。',ready:'開くボタンでこの端末から新しい管理画面を開き、下の一回用コードを入力してください。開かない場合は、下のアドレスをブラウザーのアドレス欄に貼り付けてください。ペア、ネットワーク、待受、アプリの準備状態は別々です。進行状況は新しい画面で確認してください。',open:'新しいローカル管理を開く',manual:'下のアドレスをブラウザーのアドレス欄に貼り付け、一回用コードを入力してください。自動で開く操作はできないか、結果が不明です。',code:'新しい一回用コード: ',failed:'続行の結果が不明、または続行できません。自動再試行は行いません。現在のローカル管理状態を確認してから再確認してください。',cancelled:'中止を要求しました。保存済みの確認は取り消されません。',expired:'元の確認期限が切れました。現在のローカル管理画面で再確認してください。'}};
let t=words.en;
const request=async path=>{const r=await fetch(path,{method:'POST',credentials:'omit',cache:'no-store',redirect:'error',headers:{'Content-Type':'application/json','X-Handoff-Token':token},body:'{}',signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error('handoff');return r.json()};
const clear=()=>{stopped=true;clearTimeout(polling);clearTimeout(expiry);el('continue').hidden=true;el('cancel').hidden=true;el('code').textContent='';el('management').hidden=true;el('management').value='';el('open').hidden=true;token=''};
const failed=()=>{cancel();el('message').textContent=t.failed};
const cancel=()=>{if(parentWindow)parentWindow.postMessage({kind:'sobalink-upgrade-ended'},previousOrigin);if(token)void fetch('/cancel',{method:'POST',credentials:'omit',redirect:'error',keepalive:true,headers:{'Content-Type':'application/json','X-Handoff-Token':token},body:'{}'}).catch(()=>{});clear()};
const pulse=async()=>{if(stopped)return;try{await request('/pulse');if(!stopped)polling=setTimeout(pulse,1000)}catch{failed()}};
const poll=async()=>{if(stopped)return;try{const r=await request('/status');if(stopped)return;if(r.state==='ready' && typeof r.code==='string' && r.code){const u=new URL(r.url);if(u.protocol!=='http:'||u.hostname!=='127.0.0.1'||!u.port||u.search||u.hash||u.pathname!=='/'||u.username||u.password)throw Error('address');el('message').textContent=t.ready;el('code').textContent=t.code+r.code;el('management').value=u.origin;el('management').hidden=false;el('open').textContent=t.open;el('open').hidden=false;polling=setTimeout(pulse,1000);return}if(['failed','cancelled','ready'].includes(r.state)){failed();return}polling=setTimeout(poll,500)}catch{failed()}};
el('continue').onclick=async()=>{if(pending||stopped||!token)return;pending=true;clearTimeout(polling);el('continue').disabled=true;try{const committed=await request('/commit');if(stopped)return;if(committed.state!=='acknowledgement')throw Error('ack');const ack=await request('/ack');if(stopped)return;if(ack.state!=='restarting')throw Error('ack');el('message').textContent=t.working;void poll()}catch{failed()}};
el('management').onclick=()=>el('management').select();
el('open').onclick=async()=>{if(stopped||!token||el('open').disabled)return;el('open').disabled=true;try{const r=await request('/open');if(!stopped&&r.state!=='open-requested')el('message').textContent=t.manual}catch{if(!stopped)el('message').textContent=t.manual}};
el('cancel').onclick=()=>{cancel();el('message').textContent=t.cancelled};
window.addEventListener('pagehide',cancel);
window.addEventListener('pageshow',e=>{if(e.persisted){clear();el('message').textContent=t.failed}});
const announce=()=>{if(parentWindow&&!received)parentWindow.postMessage({kind:'sobalink-upgrade-ready'},previousOrigin)};
const announcement=setInterval(announce,500);announce();
window.addEventListener('message',async e=>{if(received||e.source!==parentWindow||e.origin!==previousOrigin||e.data?.kind!=='sobalink-upgrade-transfer'||typeof e.data.token!=='string'||!/^[a-f0-9]{64}$/.test(e.data.token))return;received=true;clearInterval(announcement);window.opener=null;token=e.data.token;try{const r=await request('/claim');if(stopped)return;if(typeof r.token!=='string'||!/^[a-f0-9]{64}$/.test(r.token))throw Error('claim');token=r.token;t=words[r.locale]||words.en;const remaining=Date.parse(r.review.deadline)-Date.now();if(remaining<=0||remaining>300000)throw Error('expiry');expiry=setTimeout(()=>{cancel();el('message').textContent=t.expired},remaining);document.documentElement.lang=r.locale;el('title').textContent=t.title;el('message').textContent=t.review;el('review').textContent=JSON.stringify(r.review,null,2);el('continue').textContent=t.continue;el('continue').hidden=false;el('cancel').textContent=t.cancel;el('cancel').hidden=false;polling=setTimeout(pulse,1000)}catch{failed()}});
`
