import { describe, expect, it } from 'vitest'
import { ApiError } from '../api'
import { deferred } from '../resource/fixtures.test-support'
import { ResourceCatalogController } from './controller'
import { context, fixtureTransport, localRequest, responseFor, target } from './fixtures.test-support'
import { workflows } from './workflow'
function setup() { const fixture = fixtureTransport(), errors: unknown[] = [], controller = new ResourceCatalogController(fixture.transport, error => errors.push(error)); controller.updateContext(context); controller.open(); return { ...fixture, controller, errors } }
async function select(controller: ResourceCatalogController) { await controller.loadLocal(); expect(controller.select(localRequest)).toBe(true) }
describe('explicit local catalog controller', () => {
  it('performs no transport on construction open context observation or source selection', () => { const h = setup(); h.controller.select({ schemaVersion: 1, sources: [{ kind: 'local_service' }] }); h.controller.updateContext(context); expect(h.calls).toEqual([]) })
  it('requires a freshly resolved exact local settings target without dropping categories', async () => { const h = setup(); expect(h.controller.select(localRequest)).toBe(false); expect(h.calls).toHaveLength(0); await select(h.controller); await h.controller.refresh(); expect(h.calls.map(call => call.name)).toEqual(['resource.list', 'resource.catalog.snapshot']); expect(h.calls[1].request).toEqual(localRequest) })
  it('allows an explicitly narrower selection when local settings remain unresolved', async () => { const h = setup(); h.controller.select({ schemaVersion: 1, sources: [{ kind: 'local_service' }] }); await h.controller.refresh(); expect(h.calls).toHaveLength(1); expect(h.controller.getSnapshot().candidate?.snapshot.sources).toHaveLength(1) })
  it('dispatches only once for concurrent refresh clicks and never retries', async () => { const h = setup(), pending = deferred(); h.transport.snapshot = async (request, signal) => { h.calls.push({ name: 'resource.catalog.snapshot', request, signal }); return pending.promise }; await select(h.controller); const first = h.controller.refresh(); await h.controller.refresh(); expect(h.calls).toHaveLength(2); pending.reject(new Error('lost')); await first; expect(h.calls).toHaveLength(2); expect(h.controller.getSnapshot().notice).toBe('unavailable') })
  it('makes the previous observation nonactionable during refresh and after failure', async () => { const h = setup(); await select(h.controller); await h.controller.refresh(); const source = h.controller.getSnapshot().candidate!.snapshot.sources[0], action = workflows(source, source.rows[0])[0]; expect(h.controller.resolve(action)).not.toBeNull(); const pending = deferred(); h.transport.snapshot = async () => pending.promise; const request = h.controller.refresh(); expect(h.controller.resolve(action)).toBeNull(); pending.reject(new Error('unavailable')); await request; expect(h.controller.getSnapshot().observation).toBe('stale'); expect(h.controller.resolve(action)).toBeNull() })
  it('aborts close and suppresses late success without reopening', async () => { const h = setup(), pending = deferred(); h.transport.snapshot = async (request, signal) => { h.calls.push({ name: 'resource.catalog.snapshot', request, signal }); return pending.promise }; await select(h.controller); const request = h.controller.refresh(); h.controller.close(); expect(h.calls[1].signal.aborted).toBe(true); pending.resolve(responseFor()); await request; expect(h.controller.getSnapshot().opened).toBe(false); expect(h.controller.getSnapshot().candidate).toBeNull() })
  it('invalidates pending work on source edit and Stop waiting without claiming provider cancellation', async () => { const h = setup(), pending = deferred(); h.transport.snapshot = async () => pending.promise; await select(h.controller); const request = h.controller.refresh(); h.controller.stopWaiting(); h.controller.select({ schemaVersion: 1, sources: [{ kind: 'local_service' }] }); pending.resolve(responseFor()); await request; expect(h.controller.getSnapshot().candidate).toBeNull(); expect(h.controller.getSnapshot().request?.sources).toEqual([{ kind: 'local_service' }]) })
  it('discards candidates and selectors after process auth or peer context changes', async () => { const h = setup(); await select(h.controller); await h.controller.refresh(); h.controller.updateContext({ ...context, revision: 'next-auth-context' }); expect(h.controller.getSnapshot().candidate).toBeNull(); expect(h.controller.getSnapshot().request).toBeNull(); expect(h.controller.getSnapshot().localResources).toBeNull() })
  it('retains observations on display-name-only context updates', async () => { const h = setup(); await select(h.controller); await h.controller.refresh(); const candidate = h.controller.getSnapshot().candidate; h.controller.updateContext({ ...context, peers: [{ ...context.peers[0], name: 'Another synthetic label' }] }); expect(h.controller.getSnapshot().candidate).toBe(candidate) })
  it('rejects remote keys without exact saved managed selection and never infers trust', () => { const h = setup(); expect(h.controller.select({ schemaVersion: 1, sources: [{ kind: 'remote_settings_v2', peerKey: '0'.repeat(64), target, grantId: '1'.repeat(32), grantRevision: 1 }] })).toBe(false); expect(h.calls).toHaveLength(0) })
  it('prevents dispatch after reentrant subscriber context invalidation', async () => { const h = setup(); await select(h.controller); const unsubscribe = h.controller.subscribe(() => { if (h.controller.getSnapshot().busy === 'snapshot') h.controller.updateContext({ ...context, available: false, revision: 'lost' }) }); await h.controller.refresh(); unsubscribe(); expect(h.calls.map(call => call.name)).toEqual(['resource.list']); expect(h.controller.getSnapshot().candidate).toBeNull() })
  it('does not start an old local-list request after a subscriber selects a different source', async () => {
    const h = setup(); let changed = false
    const unsubscribe = h.controller.subscribe(() => { if (!changed) { changed = true; h.controller.select({ schemaVersion: 1, sources: [{ kind: 'local_service' }] }) } })
    await h.controller.loadLocal(); unsubscribe()
    expect(h.calls).toHaveLength(0); expect(h.controller.getSnapshot().request?.sources).toEqual([{ kind: 'local_service' }])
  })
  it('prevents source acceptance after reentrant selection notification closes the view', () => { const h = setup(); const unsubscribe = h.controller.subscribe(() => { if (h.controller.getSnapshot().opened) h.controller.close() }); expect(h.controller.select({ schemaVersion: 1, sources: [{ kind: 'local_service' }] })).toBe(false); unsubscribe(); expect(h.controller.getSnapshot().request).toBeNull() })
  it('clears visible data and forwards only current authentication loss', async () => { const h = setup(); await select(h.controller); const error = new ApiError('unauthenticated', ''); h.transport.snapshot = async () => { throw error }; await h.controller.refresh(); expect(h.errors).toEqual([error]); expect(h.controller.getSnapshot().candidate).toBeNull(); expect(h.controller.getSnapshot().opened).toBe(false) })
  it('ignores a late authentication error after a new context', async () => { const h = setup(), pending = deferred(); await select(h.controller); h.transport.snapshot = async () => pending.promise; const request = h.controller.refresh(); h.controller.updateContext({ ...context, revision: 'new-context' }); pending.reject(new ApiError('unauthenticated', '')); await request; expect(h.errors).toEqual([]) })
})
