import type { Locale } from '../api'
export const catalogEnglish = {
  title: 'Resources', intro: 'Inspect selected local settings, saved services and transfer activity. Each source is observed separately; this view is not continuously watched.',
  scope: 'Selected sources', local_settings: 'Local settings', local_service: 'Saved services', transfer_activity: 'Transfer activity', remote_service: 'Shared service observations', remote_settings_v1: 'Remote settings (inspection v1)', remote_settings_v2: 'Remote settings (management v2)',
  loadLocal: 'Load local settings selection', chooseTarget: 'Choose a local resource', unresolved: 'Local settings are unresolved. Load and select a resource, or explicitly deselect this category before refreshing.',
  remote: 'One selected remote device', peer: 'Exact peer', choosePeer: 'Choose one peer', remoteSettings: 'Include remote settings', remoteServices: 'Include cached shared services', protocol: 'Settings protocol', resourceId: 'Resource ID', grantId: 'Existing grant ID', grantRevision: 'Existing grant revision',
  remoteHint: 'A saved peer, trust or incoming grant does not authorize remote inspection. Supply the exact existing selector. No remote catalog enumeration is performed.',
  refresh: 'Refresh selected sources', stop: 'Stop waiting', stoppedHint: 'Stopping a read does not recall work already received by a provider.', empty: 'Confirmed empty at the observed time.', unread: 'No catalog observation yet.', stale: 'Previous observation: actions disabled.', partial: 'Some selected sources are incomplete.', complete: 'All selected sources were fully observed.',
  current: 'Observed', unconfirmed: 'Unconfirmed', unavailable: 'Unavailable. Verify the current local context and explicitly refresh.', unsupported: 'Unsupported by the selected source', invalid: 'The response could not be validated.', limited: 'This view reached a finite limit. Select fewer categories or review the existing page budget.', contextChanged: 'The owning context changed. Select sources again.', selectionRequired: 'Complete the exact source selection before refreshing.', contextUnavailable: 'Current authenticated local context is unavailable. Refresh the application state.',
  checkedAt: 'Observed at', count: 'Rows', unknown: 'Unknown', identity: 'Identity', persistent: 'Persistent identity', activation: 'Activation identity', process: 'Process-local identity', direction: 'Direction', incoming: 'Incoming', outgoing: 'Outgoing', state: 'Observed state', requested: 'Requested', effective: 'Effective', files: 'Concurrent files', perPeer: 'Concurrent files per peer', default: 'Default', bytes: 'Completed / total bytes',
  inspect_settings: 'Open settings inspection', review_settings: 'Open settings review', review_saved_service: 'Open saved service', review_service_start: 'Open start review workflow', review_service_stop: 'Open stop review workflow', open_transfer: 'Open transfer details',
  discoveryHint: 'Shared-service observations are stale and have no connection action until publication-origin validation is available.',
  actionHint: 'These buttons only open existing workflows. Fresh inspection or review and explicit confirmation are still required.',
  limitsHint: 'The browser additionally bounds this view to 8,192 rows and 8 MiB. Provider limits may be smaller; no capacity setting is changed.',
  openServiceConnections: 'Open service connections', genericServiceNavigation: 'Open a blank connection form for this selected peer. No observed service is selected and no connection is started.',
  forward: 'Forward', share: 'Share', finite: 'Finite', 'until-stopped': 'Until stopped', 'until-revoked': 'Until revoked', saved: 'Saved', starting: 'Starting', active: 'Active', reconnecting: 'Reconnecting', failed: 'Failed', expired: 'Expired', stopped: 'Stopped', 'awaiting-acceptance': 'Awaiting acceptance', queued: 'Queued', transferring: 'Transferring', saving: 'Saving', completed: 'Completed', cancelled: 'Cancelled', declined: 'Declined',
  missingSelection: 'The selected resource is no longer represented. Refresh the existing workflow.',
} as const
export type CatalogTextKey = keyof typeof catalogEnglish
export const catalogJapanese: Record<CatalogTextKey, string> = {
  title: 'リソース', intro: '選択したローカル設定、保存済みサービス、転送状況を確認します。各情報は個別に取得され、この画面では継続監視しません。',
  scope: '選択した情報源', local_settings: 'ローカル設定', local_service: '保存済みサービス', transfer_activity: '転送状況', remote_service: '共有サービスの観測情報', remote_settings_v1: 'リモート設定（参照 v1）', remote_settings_v2: 'リモート設定（管理 v2）',
  loadLocal: 'ローカル設定の選択肢を取得', chooseTarget: 'ローカルリソースを選択', unresolved: 'ローカル設定が未解決です。取得してリソースを選ぶか、この項目を明示的に外してから更新してください。',
  remote: '選択した1台のリモート端末', peer: '正確なピア', choosePeer: 'ピアを1台選択', remoteSettings: 'リモート設定を含める', remoteServices: '保存された共有サービス情報を含める', protocol: '設定プロトコル', resourceId: 'リソースID', grantId: '既存の許可ID', grantRevision: '既存の許可リビジョン',
  remoteHint: '保存済みピア、信頼、受信側の許可だけではリモート参照は許可されません。既存の正確な選択情報が必要です。リモートカタログの列挙は行いません。',
  refresh: '選択した情報源を更新', stop: '待機を終了', stoppedHint: '参照の待機を終了しても、提供側が受け取った処理は取り消されません。', empty: '観測時点で空であることを確認しました。', unread: 'カタログ情報はまだ取得していません。', stale: '以前の観測情報：操作は無効です。', partial: '選択した情報源の一部が未完了です。', complete: '選択したすべての情報源を取得しました。',
  current: '観測済み', unconfirmed: '未確認', unavailable: '利用できません。現在のローカル状態を確認して明示的に更新してください。', unsupported: '選択した情報源では未対応', invalid: '応答を検証できませんでした。', limited: '表示の有限上限に達しました。項目を減らすか、既存のページ上限を確認してください。', contextChanged: '処理主体の状態が変わりました。情報源を選び直してください。', selectionRequired: '正確な情報源の選択を完了してから更新してください。', contextUnavailable: '現在の認証済みローカル状態を確認できません。アプリの状態を更新してください。',
  checkedAt: '観測日時', count: '行数', unknown: '不明', identity: '識別子', persistent: '永続的な識別子', activation: '起動中の識別子', process: 'プロセス内の識別子', direction: '方向', incoming: '受信', outgoing: '送信', state: '観測した状態', requested: '指定値', effective: '有効値', files: '同時ファイル数', perPeer: 'ピアごとの同時ファイル数', default: '既定値', bytes: '完了 / 合計バイト数',
  inspect_settings: '設定の参照を開く', review_settings: '設定の確認を開く', review_saved_service: '保存済みサービスを開く', review_service_start: '開始確認の画面を開く', review_service_stop: '停止確認の画面を開く', open_transfer: '転送の詳細を開く',
  openServiceConnections: 'サービス接続の画面を開く', genericServiceNavigation: '選択したピアの空の接続フォームを開きます。観測されたサービスは選択されず、接続も開始しません。',
  forward: '転送接続', share: '共有', finite: '期限付き', 'until-stopped': '停止するまで', 'until-revoked': '取り消すまで', saved: '保存済み', starting: '開始中', active: '稼働中', reconnecting: '再接続中', failed: '失敗', expired: '期限切れ', stopped: '停止済み', 'awaiting-acceptance': '受け入れ待ち', queued: '待機中', transferring: '転送中', saving: '保存中', completed: '完了', cancelled: '取り消し済み', declined: '辞退済み',
  discoveryHint: '共有サービス情報は過去の観測です。公開元の検証が実装されるまで接続操作は表示しません。', actionHint: 'ボタンは既存の画面を開くだけです。新しい参照や確認と、明示的な確定が引き続き必要です。', limitsHint: 'ブラウザー表示にも8,192行・8 MiBの上限があります。提供側の上限はさらに小さい場合があります。容量設定は変更しません。', missingSelection: '選択したリソースは現在の一覧にありません。既存の画面を更新してください。',
}
export function catalogText(locale: Locale, key: CatalogTextKey): string { return (locale === 'ja' ? catalogJapanese : catalogEnglish)[key] }
