import { describe, expect, it } from 'vitest'
import { currentTransfer, navigation, workflows } from './workflow'
import { appState, localRequest, processId, remoteSelection, responseFor, sourceFor, target } from './fixtures.test-support'
import type { CatalogRow } from './types'
describe('inert exact catalog workflows', () => {
  it('maps local and v2 settings to navigation while v1 remains inspect-only', () => {
    for (const kind of ['local_settings', 'remote_settings_v1', 'remote_settings_v2'] as const) { const source = sourceFor(kind === 'local_settings' ? { kind, target } : { kind, target, peerKey: remoteSelection.peerKey, grantId: remoteSelection.selector.grantId, grantRevision: 1 }); expect(workflows(source, source.rows[0]).map(w => w.kind)).toEqual(kind === 'remote_settings_v1' ? ['inspect_settings'] : ['inspect_settings', 'review_settings']) }
  })
  it('offers failed saved services inspection only and never dispatches start stop or apply', () => { const source = sourceFor({ kind: 'local_service' }); const row = source.rows[0]; if (!('localService' in row)) throw new Error('Fixture'); const failed: CatalogRow = { ...row, localService: { ...row.localService, state: 'failed' } }; expect(workflows({ ...source, rows: [failed] }, failed).map(w => w.kind)).toEqual(['review_saved_service']) })
  it('disables stale incomplete unavailable and foreign-row workflows', () => { const source = sourceFor({ kind: 'local_service' }); expect(workflows({ ...source, state: 'stale' }, source.rows[0])).toEqual([]); expect(workflows({ ...source, complete: false }, source.rows[0])).toEqual([]); expect(workflows(source, structuredClone(source.rows[0]))).toEqual([]) })
  it('never derives a catalog discovery connect action', () => { const source = sourceFor({ kind: 'remote_service', peerId: remoteSelection.peerKey }); expect(workflows(source, source.rows[0])).toEqual([]); expect(workflows({ ...source, state: 'current' }, source.rows[0])).toEqual([]) })
  it('preserves exact original transfer ID direction peer and opaque process token', () => { const snapshot = responseFor(localRequest).snapshot, source = snapshot.sources[2], action = workflows(source, source.rows[0])[0], result = navigation(snapshot, action); expect(result).toEqual({ kind: 'transfer', focus: { processId, peerId: remoteSelection.peerKey, id: 'batch-synthetic', direction: 'incoming' } }); if (result?.kind !== 'transfer') throw new Error('Fixture'); expect(currentTransfer(appState, false, result.focus)).toBe(true); expect(currentTransfer(appState, true, result.focus)).toBe(false); expect(currentTransfer({ ...appState, resourceCatalogProcessId: 'a'.repeat(64) }, false, result.focus)).toBe(false); expect(currentTransfer(appState, false, { ...result.focus, direction: 'outgoing' })).toBe(false); expect(currentTransfer({ ...appState, transfers: [] }, false, result.focus)).toBe(false) })
})
