import type { Locale } from './api'
export const advancedEnglish = {
  title: 'Advanced connections', intro: 'An optional authenticated SOCKS5 proxy for applications that need several approved TCP targets. For one service, use Connect to a service.',
  proxies: 'Current proxies', none: 'No running proxies', create: 'Review a new proxy', name: 'Proxy name', backend: 'Selected network', listener: 'Loopback address', localPort: 'Local proxy port', target: 'Target device', port: 'TCP port', targets: 'Allowed TCP targets', addTarget: 'Add target', removeTarget: 'Remove target', choosePeer: 'Choose a current device…', lifetime: 'Lifetime', finite: 'For a set duration', untilStopped: 'Until stopped or this process ends', seconds: 'Duration in seconds',
  review: 'Review exact scope', reviewTitle: 'Review proxy scope', reviewHint: 'Review the name, network, loopback endpoint, exact device identities and ports, and lifetime. This review opens no listener.', endpoint: 'Local endpoint', peerID: 'Device ID', host: 'Application target host', back: 'Edit scope', authenticate: 'Continue to authentication', username: 'Runtime username', password: 'Runtime password', credentials: 'Enter credentials privately. Both fields require 1–255 UTF-8 bytes. Use these credentials in the application. They are used for this process only and are never saved in profiles or exports.', start: 'Start reviewed proxy', started: 'Proxy started. Configure the application with its local endpoint and reviewed target host and TCP port. Application compatibility is unverified.', stopped: 'Proxy stopped; tracked connections are closed.', stop: 'Stop proxy', stopHint: 'Stopping closes tracked connections. It cannot cancel work an application has already accepted.', lifecycle: 'Network loss, device revocation or identity changes, expiry, logout, listener failure, or process exit stops the proxy. Restart requires a fresh review and credentials. It never starts automatically.', protocol: 'SOCKS5 TCP CONNECT only; username/password required. BIND and UDP are unsupported.', invalid: 'Choose a valid name, current device, exact unreserved TCP ports and lifetime.', noNetwork: 'Connect the selected network before reviewing a proxy.', changed: 'The current network or target details changed. Review the scope again.', startUncertain: 'The start result is uncertain. Credentials have been cleared. Refresh the proxy list before reviewing a new start.', failed: 'The operation failed. Refresh the current state and review again.', credentialInvalid: 'Enter 1–255 UTF-8 bytes in each credential field.',
  check: 'Check TCP connection', diagnosticTitle: 'TCP transport check', checkHint: 'Opens and closes one connection to this approved target. No application data is sent. TLS, login, application health and compatibility remain unverified.', effectivePorts: 'Effective approved ports', selectPort: 'One approved TCP port', invalidPort: 'Select exactly one port in the effective approved scope.', transport: 'TCP transport', reachable: 'Reachable', unreachable: 'Unreachable', checkedAt: 'Checked at', lastFailure: 'Last runtime failure', failureAt: 'Failure time', historyHint: 'Runtime history lasts until the process ends or the service definition is deleted. A successful check does not erase the last failure.', application: 'Application: unverified',
  proxy_scope_invalid: 'The scope is invalid or conflicts with a reserved port or service share. Edit the scope and review again.', proxy_review_required: 'The reviewed scope changed. Review it again before entering fresh credentials.', proxy_network_unavailable: 'Connect the selected network, then review again.', proxy_peer_unavailable: 'A selected device identity is no longer available. Refresh devices and review again.', proxy_credentials_required: 'Enter 1–255 UTF-8 bytes in each runtime credential field.', proxy_name_conflict: 'A proxy with this name is already active. Refresh the list and stop it or choose another name.', proxy_listener_capacity: 'Listener capacity is full. Stop an unused listener or review capacity settings.', proxy_listener_unavailable: 'The local proxy could not start. Choose a free loopback port and review again.', proxy_start_cancelled: 'The proxy start was cancelled or expired. Refresh the list and review before starting again.', diagnostic_service_inactive: 'Start the reviewed service and reconnect its network before checking TCP.', diagnostic_tcp_only: 'Choose an active TCP service. A generic UDP probe cannot establish application reachability.', diagnostic_port_required: 'Select exactly one effective approved TCP port.', diagnostic_capacity: 'TCP connection capacity is full. Retry after a connection closes.',
}
export const advancedJapanese: Record<keyof typeof advancedEnglish, string> = {
  title: '高度な接続', intro: '複数の許可済み TCP 接続先を使うアプリ向けの、任意の認証付き SOCKS5 プロキシです。サービスが 1 つなら「サービスに接続」を使えます。',
  proxies: '現在のプロキシ', none: '実行中のプロキシはありません', create: '新しいプロキシを確認', name: 'プロキシ名', backend: '選択中のネットワーク', listener: 'ループバックアドレス', localPort: 'ローカルのプロキシポート', target: '接続先の端末', port: 'TCP ポート', targets: '許可する TCP 接続先', addTarget: '接続先を追加', removeTarget: '接続先を削除', choosePeer: '現在の端末を選択…', lifetime: '有効期間', finite: '時間を指定', untilStopped: '停止またはプロセス終了まで', seconds: '有効期間（秒）',
  review: '正確な範囲を確認', reviewTitle: 'プロキシの範囲を確認', reviewHint: '名前、ネットワーク、ループバックの接続先、正確な端末 ID とポート、有効期間を確認してください。この確認では待受を開始しません。', endpoint: 'ローカルの接続先', peerID: '端末 ID', host: 'アプリの接続先ホスト', back: '範囲を編集', authenticate: '認証情報の入力へ', username: '実行中のユーザー名', password: '実行中のパスワード', credentials: '認証情報を非公開で入力してください。各欄は UTF-8 で 1〜255 バイトです。同じ認証情報をアプリに設定します。このプロセスでのみ使用し、プロファイルや書き出しには保存しません。', start: '確認したプロキシを開始', started: 'プロキシを開始しました。ローカルの接続先と、確認した接続先ホスト・TCP ポートをアプリに設定してください。アプリの互換性は未確認です。', stopped: 'プロキシを停止し、追跡中の接続を閉じました。', stop: 'プロキシを停止', stopHint: '停止すると追跡中の接続を閉じます。アプリがすでに受け付けた処理は取り消せません。', lifecycle: 'ネットワーク切断、端末の許可取消や ID 変更、期限切れ、ログアウト、待受の障害、プロセス終了で停止します。再開始には範囲の再確認と認証情報が必要です。自動開始はしません。', protocol: 'SOCKS5 の TCP CONNECT のみ。ユーザー名とパスワードが必要です。BIND と UDP は非対応です。', invalid: '有効な名前、現在の端末、予約済みでない正確な TCP ポート、有効期間を指定してください。', noNetwork: 'プロキシを確認する前に、選択中のネットワークへ接続してください。', changed: '現在のネットワークまたは接続先の情報が変わりました。範囲を再確認してください。', startUncertain: '開始結果を確認できません。認証情報は消去しました。再開始を確認する前にプロキシ一覧を更新してください。', failed: '操作に失敗しました。現在の状態を更新し、再確認してください。', credentialInvalid: '認証情報の各欄に UTF-8 で 1〜255 バイトを入力してください。',
  check: 'TCP 接続を確認', diagnosticTitle: 'TCP 到達確認', checkHint: '許可した接続先へ 1 回接続して閉じます。アプリのデータは送信しません。TLS、ログイン、アプリの状態や互換性は未確認です。', effectivePorts: '実効の許可済みポート', selectPort: '許可済み TCP ポートを 1 つ指定', invalidPort: '実効の許可範囲からポートを 1 つ指定してください。', transport: 'TCP の到達状態', reachable: '到達可能', unreachable: '到達不可', checkedAt: '確認日時', lastFailure: '直近の実行時エラー', failureAt: 'エラー日時', historyHint: '履歴はプロセス終了またはサービス定義の削除まで保持します。確認に成功しても直近のエラーは消去しません。', application: 'アプリ：未確認',
  proxy_scope_invalid: '範囲が無効か、予約済みポート・サービス共有と競合しています。範囲を編集して再確認してください。', proxy_review_required: '確認した範囲が変わりました。再確認してから認証情報を再入力してください。', proxy_network_unavailable: '選択中のネットワークへ接続し、再確認してください。', proxy_peer_unavailable: '選択した端末 ID が利用できなくなりました。端末一覧を更新し、再確認してください。', proxy_credentials_required: '認証情報の各欄に UTF-8 で 1〜255 バイトを入力してください。', proxy_name_conflict: '同じ名前のプロキシが実行中です。一覧を更新して停止するか、別の名前を指定してください。', proxy_listener_capacity: '待受の上限に達しました。不要な待受を停止するか、容量設定を確認してください。', proxy_listener_unavailable: 'ローカルのプロキシを開始できませんでした。空いているループバックポートを選び、再確認してください。', proxy_start_cancelled: '開始が取り消されたか期限切れになりました。一覧を更新し、再確認してから開始してください。', diagnostic_service_inactive: '確認済みサービスを開始し、ネットワークへ再接続してから TCP を確認してください。', diagnostic_tcp_only: '実行中の TCP サービスを選択してください。汎用 UDP 確認ではアプリへの到達を確かめられません。', diagnostic_port_required: '実効の許可済み TCP ポートを 1 つ選択してください。', diagnostic_capacity: 'TCP 接続の上限に達しました。接続が終了してから再試行してください。',
}
export function advancedText(locale: Locale, key: string): string { return (locale === 'ja' ? advancedJapanese : advancedEnglish)[key as keyof typeof advancedEnglish] || '' }
