import { StrictMode } from 'react'
import { act, fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { describe, expect, it, vi } from 'vitest'
import { App } from './App'
import { translator } from './i18n'
import type { State } from './api'
import { catalogEnglish as en } from './catalog/i18n'
import { appState, descriptor, localRequest, remoteSelection, responseFor, target } from './catalog/fixtures.test-support'
import { readCatalogRequest } from './catalog/decode'
import { ResourceCatalogController } from './catalog/controller'
import { deferred, localOperation, response as resourceResponse, type Call } from './resource/fixtures.test-support'
import { resourceEnglish as settingsText } from './resource/i18n'
type Request = { name: string; payload: unknown; requestId: string; signal: AbortSignal }
function setup(override?: (request: Request) => unknown | Promise<unknown>, initial: State = appState) {
  let state = initial, stateRead = async () => new Response(JSON.stringify(state)), presentService = true
  const commands: Request[] = []
  localStorage.setItem('sobalink.locale', 'en')
  vi.stubGlobal('fetch', vi.fn(async (path: string, init?: RequestInit) => {
    if (path === '/api/state') return stateRead()
    if (path !== '/api/command') throw new Error('Unexpected synthetic route')
    const request: Request = { ...JSON.parse(init!.body as string), signal: init!.signal as AbortSignal }; commands.push(request)
    let result = await override?.(request)
    if (result instanceof Response) return result
    if (result === undefined) {
      if (request.name === 'resource.catalog.snapshot') result = responseFor(readCatalogRequest(request.payload))
      else if (request.name.startsWith('resource.')) result = resourceResponse(request as Call)
      else if (request.name === 'profile.export') result = { disabled: true, revision: 'a'.repeat(64), profile: { version: 1, services: presentService ? [{ id: 'saved-synthetic', name: 'Synthetic service', direction: 'forward', backend: 'direct-lan', peerId: appState.peers[0].id, network: 'tcp', ports: '8080', localPort: 9000, lifetime: 'until-stopped', ttlSeconds: 0, purpose: 'web', discoverable: false, loopbackHost: '127.0.0.1' }] : [], groups: [] } }
      else throw new Error(`Unexpected synthetic command: ${request.name}`)
    }
    return new Response(JSON.stringify({ ok: true, result }))
  }))
  return { commands, setState: (next: State) => { state = next }, setStateRead: (read: () => Promise<Response>) => { stateRead = read }, missingService: () => { presentService = false } }
}
async function openCatalog() { await userEvent.click(await screen.findByRole('button', { name: en.title })); await screen.findByRole('dialog', { name: en.title }) }
async function loadAll() { await userEvent.click(screen.getByRole('button', { name: en.loadLocal })); await screen.findByRole('option', { name: target.resourceId }); await userEvent.selectOptions(screen.getByRole('combobox', { name: en.chooseTarget }), target.resourceId); await userEvent.click(screen.getByRole('button', { name: en.refresh })); await screen.findByText(en.complete) }
async function hostRefresh() { await act(async () => { fireEvent(document, new Event('visibilitychange')) }) }
async function closeDialog(title: string) { await userEvent.click(within(screen.getByRole('dialog', { name: title })).getAllByRole('button', { name: 'Close' })[0]) }
describe('mounted App unified catalog boundary', () => {
  it('opens under StrictMode without catalog polling and refreshes only the explicit exact sources', async () => { const h = setup(); render(<StrictMode><App /></StrictMode>); await openCatalog(); await hostRefresh(); expect(h.commands).toHaveLength(0); await loadAll(); expect(h.commands.map(call => call.name)).toEqual(['resource.list', 'resource.catalog.snapshot']); expect(h.commands[1].payload).toEqual(localRequest); expect(new Set(h.commands.map(call => call.requestId)).size).toBe(2); expect(h.commands.every(call => call.signal instanceof AbortSignal)).toBe(true) })
  it('opens the existing settings owner after a fresh exact list without automatically inspecting or previewing', async () => { const h = setup(); render(<App />); await openCatalog(); await loadAll(); await userEvent.click(screen.getByRole('button', { name: en.inspect_settings })); await screen.findByRole('dialog', { name: settingsText.title }); expect(h.commands.map(call => call.name)).toEqual(['resource.list', 'resource.catalog.snapshot', 'resource.list']); expect(screen.getAllByText(target.resourceId).length).toBeGreaterThan(0); expect(screen.getByText(settingsText.notChecked)).toBeVisible() })
  it('suppresses late local settings navigation after catalog close', async () => { const pending = deferred(); let lists = 0; const h = setup(request => { if (request.name === 'resource.list' && ++lists === 2) return pending.promise }); render(<App />); await openCatalog(); await loadAll(); await userEvent.click(screen.getByRole('button', { name: en.inspect_settings })); await closeDialog(en.title); await act(async () => { pending.resolve({ schemaVersion: 1, resources: [descriptor] }) }); expect(screen.queryByRole('dialog', { name: settingsText.title })).not.toBeInTheDocument(); expect(h.commands.filter(call => call.name === 'resource.list')).toHaveLength(2); expect(h.commands[2].signal.aborted).toBe(true) })
  it('does not let an older settings navigation close a newer explicitly opened settings modal', async () => { const pending = deferred(); let lists = 0; setup(request => { if (request.name === 'resource.list' && ++lists === 2) return pending.promise }); render(<App />); await openCatalog(); await loadAll(); await userEvent.click(screen.getByRole('button', { name: en.inspect_settings })); await closeDialog(en.title); await userEvent.click(screen.getByRole('button', { name: translator('en')('settings') })); await userEvent.click(screen.getByRole('button', { name: settingsText.title })); await screen.findByRole('dialog', { name: settingsText.title }); await act(async () => { pending.resolve({ schemaVersion: 1, resources: [descriptor] }) }); expect(screen.getByRole('dialog', { name: settingsText.title })).toBeVisible(); expect(screen.getByRole('button', { name: settingsText.loadLocal })).toBeEnabled() })
  it('does not activate a settings destination after source-close subscribers navigate away', async () => {
    let owner: ResourceCatalogController | undefined
    const original = ResourceCatalogController.prototype.open
    vi.spyOn(ResourceCatalogController.prototype, 'open').mockImplementation(function (this: ResourceCatalogController) { owner = this; original.call(this) })
    setup(); render(<App />); await openCatalog(); await loadAll(); let invalidated = false
    const unsubscribe = owner!.subscribe(() => { if (!invalidated && !owner!.getSnapshot().opened) { invalidated = true; window.dispatchEvent(new PopStateEvent('popstate')) } })
    await userEvent.click(screen.getByRole('button', { name: en.inspect_settings })); await waitFor(() => expect(invalidated).toBe(true)); unsubscribe()
    expect(screen.queryByRole('dialog', { name: settingsText.title })).not.toBeInTheDocument()
  })
  it('does not activate a saved-service destination after source-close context invalidation', async () => {
    let owner: ResourceCatalogController | undefined
    const original = ResourceCatalogController.prototype.open
    vi.spyOn(ResourceCatalogController.prototype, 'open').mockImplementation(function (this: ResourceCatalogController) { owner = this; original.call(this) })
    const h = setup(); render(<App />); await openCatalog(); await loadAll(); let invalidated = false
    const unsubscribe = owner!.subscribe(() => { if (!invalidated && !owner!.getSnapshot().opened) { invalidated = true; owner!.updateContext({ ...owner!.getSnapshot().context, available: false, revision: 'synthetic-auth-loss' }) } })
    await userEvent.click(screen.getByRole('button', { name: en.review_saved_service })); unsubscribe()
    expect(screen.queryByRole('dialog', { name: 'Saved services' })).not.toBeInTheDocument(); expect(h.commands.some(call => call.name === 'profile.export')).toBe(false)
  })
  it('opens an exact saved service selection without starting stopping or pre-reviewing it', async () => { const h = setup(); render(<App />); await openCatalog(); await loadAll(); await userEvent.click(screen.getByRole('button', { name: en.review_service_start })); await screen.findByRole('dialog', { name: 'Saved services' }); const selected = await screen.findByRole('checkbox', { name: /Synthetic service/ }); expect(selected).toBeChecked(); expect(h.commands.map(call => call.name)).toEqual(['resource.list', 'resource.catalog.snapshot', 'profile.export']); expect(screen.getByRole('button', { name: 'Review start' })).toBeEnabled() })
  it('shows a missing saved selection instead of choosing a substitute', async () => { const h = setup(); h.missingService(); render(<App />); await openCatalog(); await loadAll(); await userEvent.click(screen.getByRole('button', { name: en.review_saved_service })); await screen.findByText(en.missingSelection); expect(h.commands.some(call => call.name === 'services.start' || call.name === 'services.stop' || call.name === 'service.selection')).toBe(false) })
  it('focuses only the exact original transfer direction and leaves browser history unchanged', async () => { const initial = { ...appState, transfers: [appState.transfers[0], { ...appState.transfers[0], direction: 'outgoing' as const }] }; const h = setup(undefined, initial); render(<App />); await openCatalog(); await loadAll(); const historyBefore = history.state; await userEvent.click(screen.getByRole('button', { name: en.open_transfer })); await waitFor(() => expect(document.activeElement).toHaveAttribute('data-transfer-direction', 'incoming')); expect(document.activeElement).toHaveAttribute('data-transfer-id', 'batch-synthetic'); expect(history.state).toEqual(historyBefore); expect(h.commands.some(call => call.name.startsWith('transfer.') || call.name.startsWith('peer.'))).toBe(false) })
  it('refuses forgotten transfers at click time without changing the selected device', async () => { const h = setup(); render(<App />); await openCatalog(); await loadAll(); h.setState({ ...appState, transfers: [] }); await hostRefresh(); await userEvent.click(screen.getByRole('button', { name: en.open_transfer })); await screen.findByRole('alert'); expect(screen.getByRole('dialog', { name: en.title })).toBeVisible(); expect(screen.getByRole('alert')).toHaveTextContent(en.unavailable) })
  it('clears catalog actions on same-PID process token replacement', async () => { const h = setup(); render(<App />); await openCatalog(); await loadAll(); h.setState({ ...appState, resourceCatalogProcessId: '9'.repeat(64) }); await hostRefresh(); await waitFor(() => expect(screen.queryByRole('button', { name: en.open_transfer })).not.toBeInTheDocument()); expect(screen.getByText(en.unread)).toBeVisible() })
  it('clears pending catalog work on browser navigation and suppresses its late response', async () => { const pending = deferred(); const h = setup(request => request.name === 'resource.catalog.snapshot' ? pending.promise : undefined); render(<App />); await openCatalog(); await userEvent.click(screen.getByRole('checkbox', { name: en.local_settings })); await userEvent.click(screen.getByRole('button', { name: en.refresh })); act(() => window.dispatchEvent(new PopStateEvent('popstate'))); await act(async () => { pending.resolve(responseFor({ schemaVersion: 1, sources: [{ kind: 'local_service' }, { kind: 'transfer_activity' }] })) }); expect(screen.queryByRole('dialog', { name: en.title })).not.toBeInTheDocument(); expect(h.commands[0].signal.aborted).toBe(true) })
  it('hides catalog data after failed host refresh and never accepts late success as current', async () => { const pending = deferred(); const h = setup(request => request.name === 'resource.catalog.snapshot' ? pending.promise : undefined); render(<App />); await openCatalog(); await userEvent.click(screen.getByRole('checkbox', { name: en.local_settings })); await userEvent.click(screen.getByRole('button', { name: en.refresh })); h.setStateRead(async () => { throw new TypeError('Synthetic host failure') }); await hostRefresh(); await screen.findByText(en.contextUnavailable); await act(async () => { pending.resolve(responseFor({ schemaVersion: 1, sources: [{ kind: 'local_service' }, { kind: 'transfer_activity' }] })) }); expect(screen.queryByText('Synthetic service')).not.toBeInTheDocument(); expect(h.commands).toHaveLength(1) })
  it('opens the exact remote W1 selector inertly without remote inspect preview or fallback', async () => {
    const h = setup(); render(<App />); await openCatalog(); await userEvent.click(screen.getByRole('checkbox', { name: en.local_settings })); await userEvent.click(screen.getByText(en.remote)); await userEvent.selectOptions(screen.getByRole('combobox', { name: en.peer }), remoteSelection.peerKey); await userEvent.click(screen.getByRole('checkbox', { name: en.remoteSettings })); await userEvent.selectOptions(screen.getByRole('combobox', { name: en.protocol }), '2'); await userEvent.type(screen.getByRole('textbox', { name: en.resourceId }), target.resourceId); await userEvent.type(screen.getByRole('textbox', { name: en.grantId }), remoteSelection.selector.grantId); await userEvent.type(screen.getByRole('textbox', { name: en.grantRevision }), '1'); await userEvent.click(screen.getByRole('button', { name: en.refresh })); await userEvent.click(await screen.findByRole('button', { name: en.review_settings })); await screen.findByRole('dialog', { name: settingsText.title }); expect(screen.getByRole('combobox', { name: settingsText.peer })).toHaveValue(remoteSelection.peerKey); expect(screen.getByRole('textbox', { name: settingsText.resourceId })).toHaveValue(target.resourceId); expect(h.commands.map(call => call.name)).toEqual(['resource.catalog.snapshot'])
  })
  it('displays selected cached discovery as stale with no catalog connect or discovery refresh', async () => {
    const h = setup(); render(<App />); await openCatalog(); await userEvent.click(screen.getByRole('checkbox', { name: en.local_settings })); await userEvent.click(screen.getByText(en.remote)); await userEvent.selectOptions(screen.getByRole('combobox', { name: en.peer }), remoteSelection.peerKey); await userEvent.click(screen.getByRole('checkbox', { name: en.remoteServices })); await userEvent.click(screen.getByRole('button', { name: en.refresh })); const source = await screen.findByRole('region', { name: en.remote_service }); expect(within(source).queryByRole('button')).not.toBeInTheDocument(); expect(source).toHaveTextContent(en.discoveryHint); expect(h.commands.map(call => call.name)).toEqual(['resource.catalog.snapshot'])
  })
  it('does not resurrect catalog data when a late state success follows catalog authentication loss', async () => {
    const pendingSnapshot = deferred(), pendingState = deferred<Response>(), h = setup(request => request.name === 'resource.catalog.snapshot' ? pendingSnapshot.promise : undefined); render(<App />); await openCatalog(); await userEvent.click(screen.getByRole('checkbox', { name: en.local_settings })); await userEvent.click(screen.getByRole('button', { name: en.refresh })); h.setStateRead(() => pendingState.promise); await hostRefresh(); await act(async () => { pendingSnapshot.resolve(new Response(JSON.stringify({ code: 'unauthenticated' }), { status: 401 })) }); await waitFor(() => expect(screen.queryByRole('dialog', { name: en.title })).not.toBeInTheDocument()); await act(async () => { pendingState.resolve(new Response(JSON.stringify(appState))) }); expect(screen.queryByRole('button', { name: en.title })).not.toBeInTheDocument(); expect(screen.queryByText('Synthetic service')).not.toBeInTheDocument()
  })
  it('preserves the W1 ambiguous-apply barrier across catalog navigation without replay', async () => {
    const pending = deferred(), h = setup(request => request.name === 'resource.apply' ? pending.promise : undefined); render(<App />); await openCatalog(); await loadAll(); await userEvent.click(screen.getByRole('button', { name: en.inspect_settings })); await screen.findByRole('dialog', { name: settingsText.title }); await userEvent.click(screen.getByRole('button', { name: settingsText.refresh })); await waitFor(() => expect(screen.getByRole('button', { name: settingsText.preview })).toBeEnabled()); await userEvent.click(screen.getByRole('button', { name: settingsText.preview })); await userEvent.click(await screen.findByRole('checkbox', { name: settingsText.confirmation })); await userEvent.click(screen.getByRole('button', { name: settingsText.apply })); await closeDialog(settingsText.title)
    await openCatalog(); await loadAll(); await userEvent.click(screen.getByRole('button', { name: en.inspect_settings })); await screen.findByRole('dialog', { name: settingsText.title }); expect(screen.getByText(settingsText.blocked)).toBeVisible(); await act(async () => { pending.resolve(localOperation) }); expect(screen.getByText(settingsText.blocked)).toBeVisible(); expect(h.commands.filter(call => call.name === 'resource.apply')).toHaveLength(1); expect(h.commands.some(call => call.name === 'resource.operation.status')).toBe(false)
  })
})
