import type { Locale } from './api'
export const clientEnglish = {
  network_error: 'Could not reach sobalink. If saving was interrupted it may have completed; reconnect, then preview again to check the saved result before retrying.',
  remoteHosts: 'Current network addresses',
  planned: 'Planned / not saved',
  advanced: 'Connection helpers', setup: 'Save a RustDesk group', settings: 'Client settings', groupSettings: 'Settings for selected services', intro: 'Save four reviewed forwards for an existing RustDesk server. Saving opens no listeners or permissions. Start the saved group separately after reviewing it.',
  name: 'Group name', backend: 'Saved network', idPeer: 'ID server device', relayPeer: 'Relay server device', pick: 'Choose a current device…', exactID: 'Exact saved device ID', offline: 'A device ID may be saved while offline. This does not verify identity, server permission or availability; starting checks the current network.', publicKey: 'RustDesk server public key', keyHint: 'Paste only the server’s public key (32 bytes encoded as base64). Never enter a private key or password.', idPort: 'Remote ID port (TCP and UDP)', relayPort: 'Remote relay port (TCP)', localIdPort: 'Local ID port (TCP and UDP)', localRelayPort: 'Local relay port (TCP)', portHint: 'The NAT TCP flow uses ID port minus one on each side. Review the separate ID and relay ports from your server configuration.', review: 'Review four flows', reviewTitle: 'Review RustDesk group', save: 'Save reviewed group', saved: 'Group saved. No services were started.', alreadySaved: 'These exact settings are already saved. No services were started.', manage: 'Open saved group', back: 'Back to settings', invalid: 'Review the group name, exact device IDs, public key and ports. ID ports must be 1025–65535; relay ports 1024–65535, without TCP overlap.',
  flows: 'Exact forwarding flows', nat: 'NAT test', id: 'ID server', heartbeat: 'Heartbeat', relay: 'Relay server', peer: 'Device ID', remotePort: 'Remote port', endpoint: 'Local endpoint', lifetime: 'Lifetime', readiness: 'Listener readiness', ready: 'Ready', notReady: 'Not ready', savedLifetime: 'Saved lifetime', actual: 'Current saved endpoints', idServer: 'ID server setting', relayServer: 'Relay server setting', proxy: 'RustDesk proxy setting', blank: 'Leave blank', udp: 'RustDesk UDP setting', enabled: 'Keep enabled', suffix: 'Remote ID suffix', unverified: 'Application unverified. Listener readiness does not prove application compatibility or remote control success.',
  hintsIntro: 'These settings come from the current saved definitions. Copy only the values you need into your client. No external application is launched or configured.', refresh: 'Refresh settings', copy: 'Copy value', copied: 'Copied', copyFailed: 'Could not copy. Select and copy the text manually.', ssh: 'SSH command', hostKey: 'SSH HostKeyAlias', http: 'HTTP candidate', remoteEndpoints: 'Current network endpoints', mappings: 'Exact local → remote port mappings', noEndpoints: 'Current network addresses unavailable', empty: 'No saved client settings are available for this selection.',
  rustdesk_name_invalid: 'Choose a shorter valid group name; each flow adds a role suffix.', rustdesk_peer_invalid: 'Select the immutable ID-server and relay device IDs.', rustdesk_key_invalid: 'Enter only a valid base64 RustDesk public key containing 32 bytes.', rustdesk_port_invalid: 'ID ports must be 1025–65535 and relay ports 1024–65535. NAT uses the preceding ID port.', rustdesk_port_overlap: 'The relay TCP port must differ from the ID and NAT TCP ports on the same device.', rustdesk_group_conflict: 'Another saved group uses this name with different settings. Choose a new group name or inspect that existing group.', rustdesk_revision_conflict: 'The profile or setup changed. Preview the four flows and public key again before saving.', rustdesk_group_inconsistent: 'The saved RustDesk role relationships changed. Reload and inspect the group before using its settings.', rustdesk_group_required: 'Choose a saved RustDesk group.', group_not_found: 'This saved group no longer exists. Reload saved services.', request_failed: 'Could not load or save these settings. Review the fields and retry; if saving was interrupted, preview again to check whether it was saved.', invalid_response: 'The returned settings could not be verified. Refresh and review again.',
  protectedGroup: 'This group has RustDesk role metadata. Use a new group name for a different selection; changing those relationships requires an explicit metadata-detachment review in the CLI.',
} as const
export const clientJapanese: Record<keyof typeof clientEnglish, string> = {
  network_error: 'sobalink に接続できませんでした。保存が中断した場合は完了している可能性があります。再接続し、プレビューで保存結果を確認してから再試行してください。',
  remoteHosts: '現在のネットワークアドレス',
  planned: '予定・未保存',
  advanced: '接続設定の補助', setup: 'RustDesk グループを保存', settings: 'クライアント設定', groupSettings: '選択したサービスの設定', intro: '既存の RustDesk サーバー用に、確認した4つの転送を保存します。保存だけでは待受や許可を開始しません。保存済みグループを別途確認して開始してください。',
  name: 'グループ名', backend: '保存するネットワーク', idPeer: 'ID サーバーの端末', relayPeer: 'リレーサーバーの端末', pick: '現在の端末から選択…', exactID: '保存する正確な端末 ID', offline: 'オフラインの端末 ID も保存できます。識別情報・サーバーへの許可・接続可否の確認にはなりません。開始時に現在のネットワークを確認します。', publicKey: 'RustDesk サーバーの公開鍵', keyHint: 'サーバーの公開鍵だけを貼り付けてください（32バイトの base64 形式）。秘密鍵やパスワードは入力しないでください。', idPort: '接続先 ID ポート（TCP・UDP）', relayPort: '接続先リレーポート（TCP）', localIdPort: 'ローカル ID ポート（TCP・UDP）', localRelayPort: 'ローカルリレーポート（TCP）', portHint: 'NAT 用 TCP は双方の ID ポートから1を引いた番号を使います。サーバー設定の ID・リレーポートをそれぞれ確認してください。', review: '4つの通信経路を確認', reviewTitle: 'RustDesk グループを確認', save: '確認したグループを保存', saved: 'グループを保存しました。サービスは開始していません。', alreadySaved: 'この設定はすでに保存済みです。サービスは開始していません。', manage: '保存済みグループを開く', back: '設定に戻る', invalid: 'グループ名・正確な端末 ID・公開鍵・ポートを確認してください。ID は1025〜65535、リレーは1024〜65535で、TCP が重複しないようにします。',
  flows: '正確な転送経路', nat: 'NAT テスト', id: 'ID サーバー', heartbeat: 'ハートビート', relay: 'リレーサーバー', peer: '端末 ID', remotePort: '接続先ポート', endpoint: 'ローカル接続先', lifetime: '有効期間', readiness: '待受の準備', ready: '準備完了', notReady: '未準備', savedLifetime: '保存済みの有効期間', actual: '現在の保存済み接続先', idServer: 'ID サーバー設定', relayServer: 'リレーサーバー設定', proxy: 'RustDesk のプロキシ設定', blank: '空欄のまま', udp: 'RustDesk の UDP 設定', enabled: '有効のまま', suffix: '接続先 ID の末尾', unverified: 'アプリの動作は未確認です。待受の準備完了はアプリの互換性や遠隔操作の成功を示しません。',
  hintsIntro: '現在の保存済み定義から取得した設定です。必要な値だけをクライアントへコピーしてください。外部アプリの起動・設定変更は行いません。', refresh: '設定を再読み込み', copy: '値をコピー', copied: 'コピーしました', copyFailed: 'コピーできませんでした。文字列を選択して手動でコピーしてください。', ssh: 'SSH コマンド', hostKey: 'SSH HostKeyAlias', http: 'HTTP の候補', remoteEndpoints: '現在のネットワーク接続先', mappings: '正確なローカル → 接続先ポートの対応', noEndpoints: '現在のネットワークアドレスは取得できません', empty: '選択した対象の保存済みクライアント設定はありません。',
  rustdesk_name_invalid: '各経路の接尾辞が入るよう、短い有効なグループ名を指定してください。', rustdesk_peer_invalid: 'ID・リレーサーバーの固定の端末 ID を選択してください。', rustdesk_key_invalid: '32バイトを base64 で表した有効な RustDesk 公開鍵だけを入力してください。', rustdesk_port_invalid: 'ID は1025〜65535、リレーは1024〜65535です。NAT は ID の1つ前のポートを使います。', rustdesk_port_overlap: '同じ端末のリレー TCP ポートは ID・NAT TCP ポートと異なる番号にしてください。', rustdesk_group_conflict: 'この名前には異なる設定のグループが保存されています。新しい名前を指定するか、既存グループを確認してください。', rustdesk_revision_conflict: 'プロファイルまたは設定が変わりました。4つの経路と公開鍵をもう一度確認してから保存してください。', rustdesk_group_inconsistent: '保存済み RustDesk の役割の対応が変わりました。再読み込みし、グループを確認してから使用してください。', rustdesk_group_required: '保存済み RustDesk グループを選択してください。', group_not_found: 'このグループは削除されています。保存サービスを再読み込みしてください。', request_failed: '設定を取得・保存できませんでした。入力内容を確認して再試行してください。保存が中断した場合は、再度プレビューして保存済みかを確認してください。', invalid_response: '応答の設定を確認できませんでした。再読み込みして確認してください。',
  protectedGroup: 'このグループには RustDesk の役割情報があります。異なる選択には新しいグループ名を使ってください。役割の対応を変更する場合は CLI で役割情報の解除を明示的に確認します。',
}
export function clientText(locale: Locale, key: string) { return (locale === 'ja' ? clientJapanese : clientEnglish)[key as keyof typeof clientEnglish] || '' }
