import type { Locale } from './api'
export const definitionsEnglish = {
  removesRustDeskMetadata: 'This replacement removes or changes the RustDesk public key and role metadata for these saved helper groups:',
  runtimeLifetime: 'Lifetime for this start', useSavedLifetime: 'Use each saved lifetime', oneHour: 'One hour', customLifetime: 'Custom duration', durationSeconds: 'Duration in seconds', runtimeHint: 'This choice applies only to this start; saved definitions stay unchanged. An active permission is never extended by retrying. Stop it explicitly before selecting a different lifetime.',
  savedDefinition: 'Definition saved and left stopped',
  mappingInvalid: 'This saved mapping needs correction before starting.', remoteReference: 'Advertised service reference',
  navTitle: 'Saved services', title: 'Saved services', intro: 'Select saved settings or a group. Review the full scope before starting or stopping services.', empty: 'No saved services yet. Save a connection or share, even when its device is unavailable.', reload: 'Reload saved services', selectAll: 'Select all', clear: 'Clear selection', group: 'Saved group', manual: 'Choose services individually', selected: 'Selected services',
  reviewStart: 'Review start', reviewStop: 'Review stop', start: 'Start reviewed services', stop: 'Stop reviewed services', scope: 'Review selected services', share: 'Share from this device', forward: 'Connect from this device', peers: 'Devices', backend: 'Network', lifetime: 'Lifetime', seconds: 'seconds', untilStopped: 'Until stopped', untilRevoked: 'Until revoked',
  startHint: 'Starting opens the listed connections and grants the listed sharing permissions for the lifetimes shown below. Review every device, port and lifetime.', stopHint: 'Stopping closes these selected services. Saved definitions remain available for a later start.', readiness: 'Listener readiness does not confirm application success or completion of remote work.', started: 'Reviewed services started; application use is still unverified.', stopped: 'Reviewed services stopped',
  groupEditor: 'Save this selection as a group', groupName: 'Group name', groupHint: 'A group saves references to these services. Saving it does not start them.', replaceGroup: 'Replace the existing group with this selection', saveGroup: 'Save group', groupSaved: 'Group saved without starting services',
  portable: 'Import and export', export: 'Download saved definitions', exportHint: 'The private download contains service names, device references, ports and groups. It excludes credentials, pairing secrets, trust, receive folders and messages. Review it before sharing.', importFile: 'Choose a definitions file', importHint: 'Import replaces saved services and groups. Your local identity, network settings and received data stay in place. All imported services remain stopped.', importReview: 'Review import', importApply: 'Replace with reviewed definitions', importTitle: 'Review replacement', currentCount: 'Saved services to replace', incomingCount: 'Incoming services', incomingGroups: 'Incoming groups', importDone: 'Definitions imported in the stopped state', stopBeforeImport: 'Stop all active services before applying this import.', invalidBundle: 'This is not a supported definitions file. Choose a version 1 export.', fileTooLarge: 'This file exceeds the current saved-configuration storage budget. Review capacity settings or choose a smaller file.',
  group_revision_conflict: 'The saved profile changed. Reload services and groups before saving this selection.', profile_revision_conflict: 'Saved definitions or the import changed. Reload and review again.', service_revision_conflict: 'Selected definitions changed. Review their current scope again.', service_owner_conflict: 'Another task owns a selected service. It was left unchanged.',
} as const
export const definitionsJapanese: Record<keyof typeof definitionsEnglish, string> = {
  removesRustDeskMetadata: 'この置き換えにより、次の補助グループの RustDesk 公開鍵と役割情報が削除または変更されます。',
  runtimeLifetime: '今回の開始に使う有効期間', useSavedLifetime: '各サービスの保存済み有効期間', oneHour: '1時間', customLifetime: '任意の期間', durationSeconds: '有効期間（秒）', runtimeHint: 'この選択は今回の開始だけに適用し、保存済み定義は変更しません。再試行で有効な許可を延長しません。異なる有効期間を選ぶ前に明示的に停止してください。',
  savedDefinition: '定義を保存しました。停止状態のままです',
  mappingInvalid: '開始前に保存済みのポート対応を修正してください。', remoteReference: '公開されたサービスの参照',
  navTitle: '保存サービス', title: '保存済みサービス', intro: '保存済み設定またはグループを選び、対象と範囲を確認してから開始・停止します。', empty: '保存済みサービスはありません。端末が利用できなくても接続・共有の定義を保存できます。', reload: '保存済みサービスを再読み込み', selectAll: 'すべて選択', clear: '選択を解除', group: '保存済みグループ', manual: 'サービスを個別に選択', selected: '選択したサービス',
  reviewStart: '開始内容を確認', reviewStop: '停止内容を確認', start: '確認したサービスを開始', stop: '確認したサービスを停止', scope: '選択したサービスを確認', share: 'この端末から共有', forward: 'この端末から接続', peers: '対象端末', backend: 'ネットワーク', lifetime: '有効期間', seconds: '秒', untilStopped: '停止するまで', untilRevoked: '取り消すまで',
  startHint: '下記の有効期間で、表示中の接続と共有の許可を開始します。すべての対象端末・ポート・有効期間を確認してください。', stopHint: '選択したサービスを停止します。保存済み設定は残り、後から開始できます。', readiness: '待受の準備完了は、アプリの動作や相手で実行した作業の完了を意味しません。', started: '確認したサービスを開始しました。アプリの動作は未確認です。', stopped: '確認したサービスを停止しました',
  groupEditor: 'この選択をグループとして保存', groupName: 'グループ名', groupHint: '対象サービスへの参照を保存します。グループを保存してもサービスは開始しません。', replaceGroup: '既存グループをこの選択で置き換える', saveGroup: 'グループを保存', groupSaved: 'サービスを開始せずにグループを保存しました',
  portable: 'インポート・エクスポート', export: '保存済み定義をダウンロード', exportHint: '非公開のダウンロードには、サービス名・端末の参照・ポート・グループが含まれます。認証情報・ペアリング情報・通信許可・受信先・メッセージは含みません。共有前に内容を確認してください。', importFile: '定義ファイルを選択', importHint: '保存済みサービスとグループを置き換えます。この端末の識別情報・ネットワーク設定・受信済みデータは維持し、読み込むサービスはすべて停止状態になります。', importReview: 'インポートを確認', importApply: '確認した定義に置き換える', importTitle: '置き換え内容を確認', currentCount: '置き換える保存済みサービス', incomingCount: '読み込むサービス', incomingGroups: '読み込むグループ', importDone: '定義を停止状態で読み込みました', stopBeforeImport: 'インポートを適用する前に、有効なサービスをすべて停止してください。', invalidBundle: '対応する定義ファイルではありません。バージョン1のエクスポートを選択してください。', fileTooLarge: '現在の設定保存容量を超えるファイルです。容量設定を確認するか、小さいファイルを選んでください。',
  group_revision_conflict: '保存済みプロファイルが変わりました。サービスとグループを再読み込みしてから保存してください。', profile_revision_conflict: '保存済み定義またはインポート内容が変わりました。再読み込みして確認してください。', service_revision_conflict: '選択した定義が変わりました。現在の範囲をもう一度確認してください。', service_owner_conflict: '選択したサービスを別のタスクが使用中です。そのサービスは変更されていません。',
}
export function definitionText(locale: Locale, key: string) { return (locale === 'ja' ? definitionsJapanese : definitionsEnglish)[key as keyof typeof definitionsEnglish] || '' }
