import type { Locale } from './api'
export const savedEditorEnglish = {
  saving: 'Saving the reviewed definition… Closing this window will not cancel a submitted save. Reopen Saved services to check the result.',
  template: 'Start from saved share', blankTemplate: 'Start with a blank share', templateHint: 'Copies the current saved settings into a new stopped draft. Review and edit the exact devices, target, protocol, ports, exclusions and lifetime before saving. No access or startup approval is copied.',
  create: 'Create saved service', createForward: 'Save a connection', createShare: 'Save a share', edit: 'Edit saved definition', copy: 'Copy saved definition', remove: 'Remove definition', intro: 'Prepare a stopped definition even when the device or network is unavailable. Saving opens no listener and grants no current access. Starting later requires a separate scope review and current permission checks.', peers: 'Exact device IDs', peerHint: 'Use one exact device ID for a connection, or distinct IDs separated by commas for a share. These are saved references, not proof of a current device, trust or reachability.', addPeer: 'Add a visible device…', backend: 'Saved network', chooseBackend: 'Choose a network…', backendHint: 'An existing definition keeps its network. Copy it to save a definition for another network.', review: 'Review stopped definition', confirm: 'Save reviewed definition', reviewTitle: 'Review saved scope', back: 'Edit this draft', saved: 'Definition saved and left stopped', invalid: 'Review the name, exact device IDs, ports, mapping, network and lifetime.', unavailable: 'Some referenced devices are not currently visible on this saved network. Saving preserves their IDs; starting still requires current validation.', duration: 'Duration in seconds', reload: 'Reload saved definition', historical: 'The advertised grant and its review are saved references. They do not prove that the grant is still available. The exact grant is checked again before any start.', manual: 'Use explicit manual ports instead', manualHint: 'This removes the advertised grant reference and review. Check the exact device and ports again before saving.', purpose: 'Purpose', active: 'Stop this service before editing its saved definition, or copy it as a new stopped definition.',
}
export const savedEditorJapanese: Record<keyof typeof savedEditorEnglish, string> = {
  saving: '確認した定義を保存しています。この画面を閉じても送信済みの保存は取り消せません。保存済みサービスを開き直して結果を確認してください。',
  template: '保存済み共有をひな形にする', blankTemplate: '空の共有から作成', templateHint: '現在の保存設定を、新しい停止状態の下書きにコピーします。保存前に端末・対象・プロトコル・ポート・除外・有効期間を確認して編集してください。アクセス許可や起動時の承認はコピーしません。',
  create: '保存サービスを作成', createForward: '接続定義を保存', createShare: '共有定義を保存', edit: '保存済み定義を編集', copy: '保存済み定義をコピー', remove: '定義を削除', intro: '端末やネットワークが利用できないときも、停止状態の定義を準備できます。保存では待受を開始せず、現在のアクセスを許可しません。後から開始するには、別途範囲の確認と現在の許可の検証が必要です。', peers: '正確な端末 ID', peerHint: '接続は端末 ID を 1 つ、共有は異なる ID をカンマで区切って指定してください。保存する参照であり、現在の端末・信頼・到達性を証明しません。', addPeer: '表示中の端末を追加…', backend: '保存するネットワーク', chooseBackend: 'ネットワークを選択…', backendHint: '既存の定義はネットワークを維持します。別のネットワーク用にはコピーして保存してください。', review: '停止状態の定義を確認', confirm: '確認した定義を保存', reviewTitle: '保存する範囲を確認', back: 'この下書きを編集', saved: '定義を保存しました。停止状態のままです', invalid: '名前、正確な端末 ID、ポートと対応、ネットワーク、有効期間を確認してください。', unavailable: '保存するネットワークで現在表示されていない端末が含まれます。保存では ID を保持し、開始時には現在の状態を検証します。', duration: '有効期間（秒）', reload: '保存済み定義を再読み込み', historical: '公開された許可とその確認内容は保存された参照です。現在も利用できる証拠ではありません。開始前に正確な許可を再確認します。', manual: '明示的な手動ポート指定に変更', manualHint: '公開された許可の参照と確認内容を削除します。保存する前に、正確な端末とポートを再確認してください。', purpose: '用途', active: '保存済み定義を編集する前にサービスを停止するか、新しい停止状態の定義としてコピーしてください。',
}
export function savedEditorText(locale: Locale, key: string) { return (locale === 'ja' ? savedEditorJapanese : savedEditorEnglish)[key as keyof typeof savedEditorEnglish] || '' }
